"""
Wrappers for launch.h
"""

LAUNCH_KEY_SUBMITJOB=			"SubmitJob"
LAUNCH_KEY_REMOVEJOB=			"RemoveJob"
LAUNCH_KEY_STARTJOB=			"StartJob"
LAUNCH_KEY_STOPJOB=			"StopJob"
LAUNCH_KEY_GETJOB=			"GetJob"
LAUNCH_KEY_GETJOBWITHHANDLES=		"GetJobWithHandles"
LAUNCH_KEY_GETJOBS=			"GetJobs"
LAUNCH_KEY_CHECKIN=			"CheckIn"

LAUNCH_JOBKEY_LABEL=			"Label"
LAUNCH_JOBKEY_DISABLED=			"Disabled"
LAUNCH_JOBKEY_USERNAME=			"UserName"
LAUNCH_JOBKEY_GROUPNAME=			"GroupName"
LAUNCH_JOBKEY_TIMEOUT=			"TimeOut"
LAUNCH_JOBKEY_INITGROUPS=		"InitGroups"
LAUNCH_JOBKEY_SOCKETS=			"Sockets"
LAUNCH_JOBKEY_EVENTSOURCES=		"EventSources"
LAUNCH_JOBKEY_INETDCOMPATIBILITY=	"inetdCompatibility"
LAUNCH_JOBKEY_PROGRAMARGUMENTS=		"ProgramArguments"
LAUNCH_JOBKEY_PROGRAM=			"Program"
LAUNCH_JOBKEY_ONDEMAND=			"OnDemand"
LAUNCH_JOBKEY_RUNATLOAD=			"RunAtLoad"
LAUNCH_JOBKEY_ROOTDIRECTORY=		"RootDirectory"
LAUNCH_JOBKEY_WORKINGDIRECTORY=		"WorkingDirectory"
LAUNCH_JOBKEY_SERVICEDESCRIPTION=	"ServiceDescription"
LAUNCH_JOBKEY_ENVIRONMENTVARIABLES=	"EnvironmentVariables"
LAUNCH_JOBKEY_USERENVIRONMENTVARIABLES=	"UserEnvironmentVariables"
LAUNCH_JOBKEY_PID=			"PID"
LAUNCH_JOBKEY_UMASK=			"Umask"
LAUNCH_JOBKEY_NICE=			"Nice"
LAUNCH_JOBKEY_LOWPRIORITYIO=		"LowPriorityIO"
LAUNCH_JOBKEY_SESSIONCREATE=		"SessionCreate"
LAUNCH_JOBKEY_SOFTRESOURCELIMITS=	"SoftResourceLimits"
LAUNCH_JOBKEY_HARDRESOURCELIMITS=	"HardResourceLimits"
LAUNCH_JOBKEY_SERVICEIPC=		"ServiceIPC"
LAUNCH_JOBKEY_STANDARDOUTPATH=		"StandardOutPath"
LAUNCH_JOBKEY_STANDARDERRORPATH=		"StandardErrorPath"
LAUNCH_JOBKEY_DEBUG=			"Debug"
LAUNCH_JOBKEY_QUEUEDIRECTORIES=		"QueueDirectories"
LAUNCH_JOBKEY_WATCHPATHS=		"WatchPaths"
LAUNCH_JOBKEY_STARTINTERVAL=		"StartInterval"
LAUNCH_JOBKEY_STARTCALENDARINTERVAL=	"StartCalendarInterval"
LAUNCH_JOBKEY_BONJOURFDS=		"BonjourFDs"

LAUNCH_JOBINETDCOMPATIBILITY_WAIT=	"Wait"

LAUNCH_JOBKEY_CAL_MINUTE=		"Minute"
LAUNCH_JOBKEY_CAL_HOUR=			"Hour"
LAUNCH_JOBKEY_CAL_DAY=			"Day"
LAUNCH_JOBKEY_CAL_WEEKDAY=		"Weekday"
LAUNCH_JOBKEY_CAL_MONTH=			"Month"

LAUNCH_JOBKEY_RESOURCELIMIT_CORE=	"Core"
LAUNCH_JOBKEY_RESOURCELIMIT_CPU=		"CPU"
LAUNCH_JOBKEY_RESOURCELIMIT_DATA=	"Data"
LAUNCH_JOBKEY_RESOURCELIMIT_FSIZE=	"FileSize"
LAUNCH_JOBKEY_RESOURCELIMIT_MEMLOCK=	"MemoryLock"
LAUNCH_JOBKEY_RESOURCELIMIT_NOFILE=	"NumberOfFiles"
LAUNCH_JOBKEY_RESOURCELIMIT_NPROC=	"NumberOfProcesses"
LAUNCH_JOBKEY_RESOURCELIMIT_RSS	=	"ResidentSetSize"
LAUNCH_JOBKEY_RESOURCELIMIT_STACK=	"Stack"

LAUNCH_JOBSOCKETKEY_TYPE=		"SockType"
LAUNCH_JOBSOCKETKEY_PASSIVE=		"SockPassive"
LAUNCH_JOBSOCKETKEY_BONJOUR=		"Bonjour"
LAUNCH_JOBSOCKETKEY_SECUREWITHKEY=	"SecureSocketWithKey"
LAUNCH_JOBSOCKETKEY_PATHNAME=		"SockPathName"
LAUNCH_JOBSOCKETKEY_PATHMODE=		"SockPathMode"
LAUNCH_JOBSOCKETKEY_NODENAME=		"SockNodeName"
LAUNCH_JOBSOCKETKEY_SERVICENAME=		"SockServiceName"
LAUNCH_JOBSOCKETKEY_FAMILY=		"SockFamily"
LAUNCH_JOBSOCKETKEY_PROTOCOL=		"SockProtocol"
LAUNCH_JOBSOCKETKEY_MULTICASTGROUP=	"MulticastGroup"

LAUNCH_DATA_DICTIONARY = 1
LAUNCH_DATA_ARRAY = 2
LAUNCH_DATA_FD = 3
LAUNCH_DATA_INTEGER = 4
LAUNCH_DATA_REAL = 5
LAUNCH_DATA_BOOL = 6
LAUNCH_DATA_STRING = 7
LAUNCH_DATA_OPAQUE = 8
LAUNCH_DATA_ERRNO = 9

from _launch import *

class file_descriptor_wrapper(int): pass
class errno_wrapper(int): pass

set_types(file_descriptor_wrapper, errno_wrapper);
del set_types
