<?
/* $Id: nav.inc,v 1.3 2004/02/21 19:47:55 ronaldoussoren Exp $ */

$section = "examples";
$navbox = array(
  "examples/index.php", "Examples",
  "examples/other.php", "Other sites",

/*
  "examples/index.php", "Example List",
  "examples/TableModel.php", "TableModel <i>Standalone</i>",
  "examples/TableModel2.php", "TableModel <i>Project Builder</i>",
  "examples/AddressBook.php", "Address Book"
  */
  );
?>
