# This file is generated by objective.metadata
#
# Last update: Sat Jul  1 14:02:26 2023
#
# flake8: noqa

import objc, sys
from typing import NewType

if sys.maxsize > 2**32:

    def sel32or64(a, b):
        return b

else:

    def sel32or64(a, b):
        return a


if objc.arch == "arm64":

    def selAorI(a, b):
        return a

else:

    def selAorI(a, b):
        return b


misc = {}
constants = """$_dispatch_data_destructor_free@@?$_dispatch_data_destructor_munmap@@?$_dispatch_data_empty@{dispatch_data_s=}$_dispatch_main_q@{dispatch_queue_s=}$_dispatch_queue_attr_concurrent@{dispatch_queue_attr_s=}$_dispatch_source_type_data_add@{dispatch_source_type_s=}$_dispatch_source_type_data_or@{dispatch_source_type_s=}$_dispatch_source_type_data_replace@{dispatch_source_type_s=}$_dispatch_source_type_mach_recv@{dispatch_source_type_s=}$_dispatch_source_type_mach_send@{dispatch_source_type_s=}$_dispatch_source_type_memorypressure@{dispatch_source_type_s=}$_dispatch_source_type_proc@{dispatch_source_type_s=}$_dispatch_source_type_read@{dispatch_source_type_s=}$_dispatch_source_type_signal@{dispatch_source_type_s=}$_dispatch_source_type_timer@{dispatch_source_type_s=}$_dispatch_source_type_vnode@{dispatch_source_type_s=}$_dispatch_source_type_write@{dispatch_source_type_s=}$"""
enums = """$DISPATCH_API_VERSION@20181008$DISPATCH_APPLY_AUTO_AVAILABLE@1$DISPATCH_AUTORELEASE_FREQUENCY_INHERIT@0$DISPATCH_AUTORELEASE_FREQUENCY_NEVER@2$DISPATCH_AUTORELEASE_FREQUENCY_WORK_ITEM@1$DISPATCH_BLOCK_ASSIGN_CURRENT@4$DISPATCH_BLOCK_BARRIER@1$DISPATCH_BLOCK_DETACHED@2$DISPATCH_BLOCK_ENFORCE_QOS_CLASS@32$DISPATCH_BLOCK_INHERIT_QOS_CLASS@16$DISPATCH_BLOCK_NO_QOS_CLASS@8$DISPATCH_IO_RANDOM@1$DISPATCH_IO_STOP@1$DISPATCH_IO_STREAM@0$DISPATCH_IO_STRICT_INTERVAL@1$DISPATCH_MACH_SEND_DEAD@1$DISPATCH_MEMORYPRESSURE_CRITICAL@4$DISPATCH_MEMORYPRESSURE_NORMAL@1$DISPATCH_MEMORYPRESSURE_WARN@2$DISPATCH_ONCE_INLINE_FASTPATH@1$DISPATCH_PROC_EXEC@536870912$DISPATCH_PROC_EXIT@2147483648$DISPATCH_PROC_FORK@1073741824$DISPATCH_PROC_SIGNAL@134217728$DISPATCH_QUEUE_PRIORITY_DEFAULT@0$DISPATCH_QUEUE_PRIORITY_HIGH@2$DISPATCH_QUEUE_PRIORITY_LOW@-2$DISPATCH_SWIFT3_OVERLAY@0$DISPATCH_TIMER_STRICT@1$DISPATCH_VNODE_ATTRIB@8$DISPATCH_VNODE_DELETE@1$DISPATCH_VNODE_EXTEND@4$DISPATCH_VNODE_FUNLOCK@256$DISPATCH_VNODE_LINK@16$DISPATCH_VNODE_RENAME@32$DISPATCH_VNODE_REVOKE@64$DISPATCH_VNODE_WRITE@2$DISPATCH_WALLTIME_NOW@18446744073709551614$"""
misc.update({})
misc.update({})
misc.update(
    {
        "DISPATCH_QUEUE_SERIAL": None,
        "DISPATCH_TARGET_QUEUE_DEFAULT": None,
        "DISPATCH_CURRENT_QUEUE_LABEL": None,
        "DISPATCH_DATA_DESTRUCTOR_DEFAULT": None,
    }
)
functions = {
    "dispatch_io_create_with_io": (
        b"@Q@@@?",
        "",
        {
            "arguments": {
                3: {
                    "block": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"i"}},
                    }
                }
            }
        },
    ),
    "dispatch_source_get_data": (b"Q@",),
    "dispatch_data_create_concat": (b"@@@",),
    "dispatch_semaphore_create": (b"@q",),
    "dispatch_activate": (b"v@",),
    "dispatch_io_set_interval": (b"v@QQ",),
    "dispatch_assert_queue_not": (b"v@",),
    "dispatch_barrier_async": (b"v@@?",),
    "dispatch_after": (b"vQ@@?",),
    "dispatch_io_get_descriptor": (b"i@",),
    "dispatch_source_set_timer": (b"v@QQQ",),
    "dispatch_get_current_queue": (b"@",),
    "dispatch_debug": (b"v@^c", "", {"variadic": True}),
    "dispatch_io_close": (b"v@Q",),
    "dispatch_source_get_mask": (b"Q@",),
    "dispatch_queue_attr_make_initially_inactive": (b"@@",),
    "dispatch_block_create": (b"@?Q@?",),
    "dispatch_block_perform": (b"vQ@?",),
    "dispatch_block_testcancel": (b"q@?",),
    "dispatch_group_async": (b"v@@@?",),
    "dispatch_read": (
        b"viQ@@?",
        "",
        {
            "arguments": {
                3: {
                    "block": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"@"}, 1: {"type": b"i"}},
                    }
                }
            }
        },
    ),
    "dispatch_assert_queue_barrier": (b"v@",),
    "dispatch_once": (b"v^q@?",),
    "dispatch_source_set_registration_handler": (b"v@@?",),
    "dispatch_retain": (b"v@",),
    "dispatch_once_f": (
        b"v^q^v^?",
        "",
        {
            "arguments": {
                2: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_async_and_wait_f": (
        b"v@^v^?",
        "",
        {
            "arguments": {
                2: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_get_context": (b"^v@",),
    "dispatch_set_target_queue": (b"v@@",),
    "dispatch_data_copy_region": (b"@@Q^Q",),
    "dispatch_async_and_wait": (b"v@@?",),
    "dispatch_workloop_set_autorelease_frequency": (b"v@Q",),
    "dispatch_notify": (b"v^v@@?",),
    "dispatch_queue_set_specific": (
        b"v@^v^v^?",
        "",
        {
            "arguments": {
                3: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_io_write": (b"v@q@@@?",),
    "dispatch_barrier_async_f": (
        b"v@^v^?",
        "",
        {
            "arguments": {
                2: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_block_cancel": (b"v@?",),
    "dispatch_group_async_f": (
        b"v@@^v^?",
        "",
        {
            "arguments": {
                3: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "_dispatch_once_f": (
        b"v^q^v^?",
        "",
        {
            "arguments": {
                2: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_apply_f": (
        b"vQ@^v^?",
        "",
        {
            "arguments": {
                3: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}, 1: {"type": b"Q"}},
                    }
                }
            }
        },
    ),
    "dispatch_set_context": (b"v@^v",),
    "dispatch_queue_attr_make_with_qos_class": (b"@@Ii",),
    "dispatch_suspend": (b"v@",),
    "dispatch_set_finalizer_f": (
        b"v@^?",
        "",
        {
            "arguments": {
                1: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_sync": (b"v@@?",),
    "dispatch_block_notify": (b"v@?@@?",),
    "dispatch_queue_create": (b"@^c@",),
    "dispatch_group_wait": (b"q@Q",),
    "dispatch_main": (b"v",),
    "dispatch_barrier_sync": (b"v@@?",),
    "dispatch_source_set_cancel_handler_f": (
        b"v@^?",
        "",
        {
            "arguments": {
                1: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_cancel": (b"v^v",),
    "dispatch_source_set_event_handler_f": (
        b"v@^?",
        "",
        {
            "arguments": {
                1: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_queue_get_specific": (b"^v@^v",),
    "dispatch_async_f": (
        b"v@^v^?",
        "",
        {
            "arguments": {
                2: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_source_set_event_handler": (b"v@@?",),
    "dispatch_time": (b"QQq",),
    "dispatch_queue_get_label": (b"^c@",),
    "dispatch_apply": (
        b"vQ@@?",
        "",
        {
            "arguments": {
                2: {
                    "block": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"Q"}},
                    }
                }
            }
        },
    ),
    "dispatch_group_enter": (b"v@",),
    "dispatch_io_create_with_path": (
        b"@Q^ciS@@?",
        "",
        {
            "arguments": {
                5: {
                    "block": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"i"}},
                    }
                }
            }
        },
    ),
    "dispatch_testcancel": (b"q^v",),
    "dispatch_io_read": (b"v@qQ@@?",),
    "dispatch_source_testcancel": (b"q@",),
    "dispatch_source_set_registration_handler_f": (
        b"v@^?",
        "",
        {
            "arguments": {
                1: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_barrier_sync_f": (
        b"v@^v^?",
        "",
        {
            "arguments": {
                2: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_group_notify_f": (
        b"v@@^v^?",
        "",
        {
            "arguments": {
                3: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_data_create_subrange": (b"@@QQ",),
    "dispatch_semaphore_signal": (b"q@",),
    "dispatch_group_create": (b"@",),
    "dispatch_barrier_async_and_wait": (b"v@@?",),
    "dispatch_queue_get_qos_class": (b"I@^i",),
    "dispatch_debugv": (selAorI(b"v@^c^c", b"v@^c[1{__va_list_tag=II^v^v}]"),),
    "dispatch_sync_f": (
        b"v@^v^?",
        "",
        {
            "arguments": {
                2: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_workloop_set_os_workgroup": (b"v@@",),
    "dispatch_get_main_queue": (b"@",),
    "dispatch_data_apply": (b"B@@?",),
    "dispatch_write": (
        b"vi@@@?",
        "",
        {
            "arguments": {
                3: {
                    "block": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"@"}, 1: {"type": b"i"}},
                    }
                }
            }
        },
    ),
    "dispatch_io_barrier": (b"v@@?",),
    "dispatch_get_global_queue": (b"@qQ",),
    "dispatch_barrier_async_and_wait_f": (
        b"v@^v^?",
        "",
        {
            "arguments": {
                2: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_walltime": (b"Q^{timespec=qq}q",),
    "dispatch_assert_queue": (b"v@",),
    "dispatch_get_specific": (b"^v^v",),
    "dispatch_after_f": (
        b"vQ@^v^?",
        "",
        {
            "arguments": {
                3: {
                    "callable": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"^v"}},
                    }
                }
            }
        },
    ),
    "dispatch_data_create": (b"@^vQ@@?",),
    "dispatch_resume": (b"v@",),
    "dispatch_semaphore_wait": (b"q@Q",),
    "dispatch_io_create": (
        b"@Qi@@?",
        "",
        {
            "arguments": {
                3: {
                    "block": {
                        "retval": {"type": b"v"},
                        "arguments": {0: {"type": b"i"}},
                    }
                }
            }
        },
    ),
    "dispatch_source_create": (b"@^{dispatch_source_type_s=}QQ@",),
    "dispatch_wait": (b"q^vQ",),
    "dispatch_io_set_high_water": (b"v@Q",),
    "dispatch_workloop_create": (b"@^c",),
    "dispatch_workloop_create_inactive": (b"@^c",),
    "_dispatch_once": (b"v^q@?",),
    "dispatch_data_create_map": (b"@@^^v^Q",),
    "dispatch_async": (b"v@@?",),
    "dispatch_group_notify": (b"v@@@?",),
    "dispatch_release": (b"v@",),
    "dispatch_block_create_with_qos_class": (b"@?QIi@?",),
    "dispatch_io_set_low_water": (b"v@Q",),
    "dispatch_data_get_size": (b"Q@",),
    "dispatch_block_wait": (b"q@?Q",),
    "dispatch_group_leave": (b"v@",),
    "dispatch_source_get_handle": (b"Q@",),
    "dispatch_set_qos_class_floor": (b"v@Ii",),
    "dispatch_source_cancel": (b"v@",),
    "dispatch_source_merge_data": (b"v@Q",),
    "dispatch_queue_attr_make_with_autorelease_frequency": (b"@@Q",),
    "dispatch_source_set_cancel_handler": (b"v@@?",),
    "_dispatch_object_validate": (b"v@",),
    "dispatch_queue_create_with_target": (b"@^c@@",),
}
aliases = {
    "DISPATCH_APPLY_QUEUE_ARG_NULLABILITY": "_Nullable",
    "DISPATCH_QUEUE_PRIORITY_BACKGROUND": "INT16_MIN",
    "dispatch_once": "_dispatch_once",
    "DISPATCH_RETURNS_RETAINED": "OS_OBJECT_RETURNS_RETAINED",
    "dispatch_once_f": "_dispatch_once_f",
}
expressions = {"DISPATCH_TIME_NOW": "(0ull)"}

# END OF FILE
