#!/bin/sh

# This is MacOS X 10.3 specific, and a hack

if [ ! -d /usr/local/bin/. ]; then
	mkdir -p /usr/local/bin
fi

cp /Library/Python/2.3/PyObjC/bin/* /usr/local/bin
if [ $? != 0 ]; then
	echo "Could not move scripts to the correct location"
	exit 1
fi

rm -r /Library/Python/2.3/PyObjC/bin
if [ $? != 0 ]; then
	echo "Could not move scripts to the correct location [2]"
	exit 1
fi

exit 0
