#!/bin/sh

# Make sure 0.8 and 0.7 are removed completely.  In the future,
# the package will auto update previous versions.

rm -rf "/Developer/ProjectBuilder Extras/Project Templates/Application/Cocoa-Python Application"

rm -rf "/Developer/Examples/PyObjC"

rm -rf "/Library/Receipts/PyObjC-0.8.pkg"
rm -rf "/Library/Receipts/PyObjC 0.7.0.pkg"

# Versions of PyObjC before 0.9 installed python files in the site-packages
# directory, from 0.9 onwards we install in site-packages/PyObjC.

for dn in AddressBook AppKit Foundation autoGil.so objc
do
	rm -rf "/usr/lib/python2.2/site-packages/${dn}"
done

# Clean up any previous install in /usr/lib/python2.2/site-packages/PyObjC.
# The new release might include fewer files than the previous one.
rm -rf /usr/lib/python2.2/site-packages/PyObjC

# Likewise for PB templates and documentation
rm -rf "/Developer/ProjectBuilder Extras/Project Templates/Application/Cocoa-Python Application"
rm -rf "/Developer/ProjectBuilder Extras/Project Templates/Application/Cocoa-Python Documented-based Application"
rm -rf "/Developer/ProjectBuilder Extras/Project Templates/Application/Cocoa-Python-ObjC Documented-based Application"
rm -rf "/Developer/ProjectBuilder Extras/Project Templates/Application/Cocoa-Python-ObjC Application"
rm -rf /Library/Developer/Documentation/PyObjC
rm -rf /Library/Developer/Examples/PyObjC

exit 0
