import AppKit  # noqa: F401
from PyObjCTools.TestSupport import TestCase, min_sdk_level, min_os_level


class TestProtocolsExisting(TestCase):
    @min_sdk_level("10.10")
    def test_protocols10_10(self):
        self.assertProtocolExists("NSAlertDelegate", AppKit)
        self.assertProtocolExists("NSApplicationDelegate", AppKit)
        self.assertProtocolExists("NSCollectionViewDelegate", AppKit)
        self.assertProtocolExists("NSDatePickerCellDelegate", AppKit)
        self.assertProtocolExists("NSDockTilePlugIn", AppKit)
        self.assertProtocolExists("NSDrawerDelegate", AppKit)
        self.assertProtocolExists("NSImageDelegate", AppKit)
        self.assertProtocolExists("NSPageControllerDelegate", AppKit)
        self.assertProtocolExists("NSPathCellDelegate", AppKit)
        self.assertProtocolExists("NSSoundDelegate", AppKit)
        self.assertProtocolExists("NSSpeechRecognizerDelegate", AppKit)
        self.assertProtocolExists("NSSpeechSynthesizerDelegate", AppKit)
        self.assertProtocolExists("NSTextFinderClient", AppKit)
        self.assertProtocolExists("NSTextStorageDelegate", AppKit)
        self.assertProtocolExists("NSTokenFieldCellDelegate", AppKit)
        self.assertProtocolExists("NSTokenFieldDelegate", AppKit)
        self.assertProtocolExists("NSUserInterfaceItemSearching", AppKit)
        self.assertProtocolExists("NSComboBoxCellDataSource", AppKit)
        self.assertProtocolExists("NSSplitViewDelegate", AppKit)
        self.assertProtocolExists("NSTabViewDelegate", AppKit)

    @min_os_level("10.6")
    def test_protocols10_6(self):
        self.assertProtocolExists("NSAnimatablePropertyContainer", AppKit)
        self.assertProtocolExists("NSAnimationDelegate", AppKit)
        self.assertProtocolExists("NSBrowserDelegate", AppKit)
        self.assertProtocolExists("NSChangeSpelling", AppKit)
        self.assertProtocolExists("NSColorPickingCustom", AppKit)
        self.assertProtocolExists("NSColorPickingDefault", AppKit)
        self.assertProtocolExists("NSComboBoxDataSource", AppKit)
        self.assertProtocolExists("NSComboBoxDelegate", AppKit)
        self.assertProtocolExists("NSControlTextEditingDelegate", AppKit)
        self.assertProtocolExists("NSDraggingInfo", AppKit)
        self.assertProtocolExists("NSGlyphStorage", AppKit)
        self.assertProtocolExists("NSIgnoreMisspelledWords", AppKit)
        self.assertProtocolExists("NSInputServerMouseTracker", AppKit)
        self.assertProtocolExists("NSInputServiceProvider", AppKit)
        self.assertProtocolExists("NSLayoutManagerDelegate", AppKit)
        self.assertProtocolExists("NSMatrixDelegate", AppKit)
        self.assertProtocolExists("NSMenuDelegate", AppKit)
        self.assertProtocolExists("NSOpenSavePanelDelegate", AppKit)
        self.assertProtocolExists("NSOutlineViewDataSource", AppKit)
        self.assertProtocolExists("NSOutlineViewDelegate", AppKit)
        self.assertProtocolExists("NSPasteboardItemDataProvider", AppKit)
        self.assertProtocolExists("NSPasteboardReading", AppKit)
        self.assertProtocolExists("NSPasteboardWriting", AppKit)
        self.assertProtocolExists("NSPathControlDelegate", AppKit)
        self.assertProtocolExists("NSPrintPanelAccessorizing", AppKit)
        self.assertProtocolExists("NSRuleEditorDelegate", AppKit)
        self.assertProtocolExists("NSTableViewDataSource", AppKit)
        self.assertProtocolExists("NSTableViewDelegate", AppKit)
        self.assertProtocolExists(
            "NSTextAttachmentCell", AppKit, "NSTextAttachmentCellProtocol"
        )
        self.assertProtocolExists("NSTextDelegate", AppKit)
        self.assertProtocolExists("NSTextFieldDelegate", AppKit)
        self.assertProtocolExists("NSTextInput", AppKit)
        self.assertProtocolExists("NSTextInputClient", AppKit)
        self.assertProtocolExists("NSTextViewDelegate", AppKit)
        self.assertProtocolExists("NSToolbarDelegate", AppKit)
        self.assertProtocolExists("NSUserInterfaceValidations", AppKit)
        self.assertProtocolExists("NSValidatedUserInterfaceItem", AppKit)
        self.assertProtocolExists("NSWindowDelegate", AppKit)

    @min_os_level("10.7")
    def test_protocols10_7(self):
        self.assertProtocolExists("NSDraggingDestination", AppKit)
        self.assertProtocolExists("NSDraggingSource", AppKit)
        self.assertProtocolExists("NSPopoverDelegate", AppKit)
        self.assertProtocolExists("NSTextFinderBarContainer", AppKit)
        self.assertProtocolExists("NSTextLayoutOrientationProvider", AppKit)
        self.assertProtocolExists("NSUserInterfaceItemIdentification", AppKit)
        self.assertProtocolExists("NSWindowRestoration", AppKit)

    @min_sdk_level("10.8")
    def test_protocols10_8(self):
        self.assertProtocolExists("NSSharingServiceDelegate", AppKit)
        self.assertProtocolExists("NSSharingServicePickerDelegate", AppKit)
