<span class="news_date">2003-07-05: </span><span class="news_headline">PyObjC 1.0b1 released</span><?php gray_line(); ?>
  <p>
 PyObjC 1.0b1 has shipped. A disk image with an installer package and the 
 sources are <a href="http://sourceforge.net/project/showfiles.php?group_id=14534">available</a>. There are many new features and bugfixes, see the 
 <a href="<? print $root; ?>NEWS-1.0b1.txt">NEWS file</a> for details. The improvements include:
 <p>
 <ul>
 <li> Improved performance and stability
 <li> Better tutorials and examples
 <li> Initial support for MacOS X 10.1
 <li> Support for the WebKit framework
 <li> Write plugin bundles in Python (requires Python 2.3)
 </ul>
 <p>
 The PyObjC installer package installs the Python packages for use with the 
 Apple provided Python 2.2 on MacOS X 10.2 as well as a number of project
 builder templates.  Users of <a href="http://homepages.cwi.nl/~jack/macpython.html#beta">MacPython 2.3</a> can install this release using the 
 PackageManager application.

<p><span class="news_date">2003-07-05: </span><span class="news_headline">CVS snapshots</span><?php gray_line(); ?>
  <P>
We now have CVS snapshots available <a href="/cvs-snapshots">here</a>. These
are automaticly generated snapshots of our CVS tree. They might not work, and
need not even compile. 

<p><span class="news_date">2003-05-07: </span><span class="news_headline">Updated tutorial</span><?php gray_line(); ?>
  <p>
The tutorial included in the 0.9 release was not entirely up-to-date, please use <a href="<? print $root; ?> doc/tutorial.php">the tutorial on this website</a>.
<p>
<span class="news_date">2003-05-02: </span><span class="news_headline">PyObjC 0.9 released</span><?php gray_line(); ?>
 <p>
 PyObjC 0.9 has shipped. A disk image with an installer package and the sources are <a href="http://sourceforge.net/project/showfiles.php?group_id=14534">available</a>. There are many new features and bugfixes, see the <a href="<? print $root; ?>NEWS-0.9.txt">NEWS file</a> for details.
 <p>
 The PyObjC installer package installs a number of examples and project builder
 templates as wel as documentation into /Developer. Users of 
 <a href="http://homepages.cwi.nl/~jack/macpython.html#beta">MacPython 2.3b1</a> can install this release using the 
 PackageManager application.
 <p>

