<?
  $macpython23="<a href=\"http://homepages.cwi.nl/~jack/macpython/\">Mac Python 2.3</a>";
?>
<span class="news_date">2004-02-20: </span><span class="news_headline">PyObjC 1.1b1 released</span><?php gray_line(); ?>
  <p>
A new prerelease of the upcoming 1.1 release of PyObjC is available. 
See the <a href="<? print $root; ?>NEWS-1.1.txt">NEWS file</a> for details.
  <p>
Please report any problem with this release at <a href="mailto:pyobjc-dev@lists.sourceforge.net">pyobjc-dev@lists.sourceforge.net</a>, or file a bugreport at 
<a href="http://sourceforge.net/tracker/?group_id=14534&atid=114534">our bugtracker</a>.
  <p>
  <ul>
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b1.tar.gz">source archive</a></li>
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b1-macosx10.2.dmg">binary installer for Mac OS X 10.2 (Python 2.2)</a></li>
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b1-macosx10.3.dmg">binary installer for Mac OS X 10.3 (Python 2.3)</a></li>
    <li><a href="<? print $root; ?>packman/pyobjc-unstable-macosx10.2.plist">PackMan Database for MacOS X 10.2 (MacPython 2.3)</a></li>
    <li><a href="<? print $root; ?>packman/pyobjc-unstable-macosx10.3.plist">PackMan Database for MacOS X 10.3 (Python 2.3)</a></li>
  </ul>
  <p>
<b>NOTE: </b>Python 2.2 support is tested less than Python 2.3 support, because
most developers have moved to Mac OS X 10.3.
  <p>

<span class="news_date">2004-02-02: </span><span class="news_headline">PyObjC 1.1a0 released</span><?php gray_line(); ?>
  <p>
A prerelease of the upcoming 1.1 release of PyObjC is available. This version 
contains numereous improvements, especially when you're using PyObjC on Panther.
See the <a href="<? print $root; ?>NEWS-1.1.txt">NEWS file</a> for details.
  <p>
There currently is no binary installer for Mac OS X 10.2, that will be made
available with the next release.

<span class="news_date">2003-10-08: </span><span class="news_headline">PyObjC 1.0 released</span><?php gray_line(); ?>
  <p>
We're happy to announce the release of PyObjC 1.0. This version fixes the bugs 
found in the last beta and adds support for Key-Value Coding, see the 
<a href="<? print $root; ?>NEWS-1.0.txt">NEWS file</a> for details.
  <p>
A disk image and the sources are <a href="http://sourceforge.net/project/showfiles.php?group_id=14534">available</a>.  Users of <? print $macpython23 ?> can install 
PyObjC using the Package Manager.
  <p>
<span class="news_date">2003-07-05: </span><span class="news_headline">PyObjC 1.0b1 released</span><?php gray_line(); ?>
  <p>
 PyObjC 1.0b1 has shipped. A disk image with an installer package and the 
 sources are <a href="http://sourceforge.net/project/showfiles.php?group_id=14534">available</a>. There are many new features and bugfixes, see the 
 <a href="<? print $root; ?>NEWS-1.0b1.txt">NEWS file</a> for details. The improvements include:
 <p>
 <ul>
 <li> Improved performance and stability
 <li> Better tutorials and examples
 <li> Initial support for MacOS X 10.1
 <li> Support for the WebKit framework
 <li> Write plugin bundles in Python (requires Python 2.3)
 </ul>
 <p>
 The PyObjC installer package installs the Python packages for use with the 
 Apple provided Python 2.2 on MacOS X 10.2 as well as a number of project
 builder templates.  Users of <? print $macpython23 ?> can install this release using the 
 PackageManager application.

<p><span class="news_date">2003-07-05: </span><span class="news_headline">CVS snapshots</span><?php gray_line(); ?>
  <P>
We now have CVS snapshots available <a href="/cvs-snapshots">here</a>. These
are automaticly generated snapshots of our CVS tree. They might not work, and
need not even compile. 

