<span class="news_date">2004-05-30: </span><span class="news_headline">PyObjC 1.1 released</span><?php gray_line(); ?>
  <p>
It has been a long, long process, but PyObjC 1.1 is finally there.  See the 
<a href="<? print $root; ?>NEWS-1.1.txt">NEWS file</a> for details.
  <p>
Click <a href="/software/">here</a> to go to the download page.
  <p>

<span class="news_date">2004-04-11: </span><span class="news_headline">PyObjC 1.1b2 released</span><?php gray_line(); ?>
  <p>
A new prerelease of the upcoming 1.1 release of PyObjC is available. 
See the <a href="<? print $root; ?>NEWS-1.1.txt">NEWS file</a> for details.
  <p>
Please report any problem with this release at <a href="mailto:pyobjc-dev@lists.sourceforge.net">pyobjc-dev@lists.sourceforge.net</a>, or file a bugreport at 
<a href="http://sourceforge.net/tracker/?group_id=14534&atid=114534">our bugtracker</a>.
  <p>
  <ul>
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b2.tar.gz">source archive</a></li>
<!--
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b1-macosx10.2.dmg">binary installer for Mac OS X 10.2 (Python 2.2)</a></li>
-->
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b2-macosx10.3.dmg">binary installer for Mac OS X 10.3 (Python 2.3)</a></li>
<!--
    <li><a href="<? print $root; ?>packman/pyobjc-unstable-macosx10.2.plist">PackMan Database for MacOS X 10.2 (MacPython 2.3)</a><br><b>NOTE: </b>currently does not contain a binary release.</li>
    <li><a href="<? print $root; ?>packman/pyobjc-unstable-macosx10.3.plist">PackMan Database for MacOS X 10.3 (Python 2.3)</a></li>
-->
  </ul>
  <p>
<b>NOTE: </b>Python 2.2 support is tested less than Python 2.3 support, because
most developers have moved to Mac OS X 10.3.
  <p>
<span class="news_date">2004-02-20: </span><span class="news_headline">PyObjC 1.1b1 released</span><?php gray_line(); ?>
  <p>
A new prerelease of the upcoming 1.1 release of PyObjC is available. 
See the <a href="<? print $root; ?>NEWS-1.1.txt">NEWS file</a> for details.
  <p>
Please report any problem with this release at <a href="mailto:pyobjc-dev@lists.sourceforge.net">pyobjc-dev@lists.sourceforge.net</a>, or file a bugreport at 
<a href="http://sourceforge.net/tracker/?group_id=14534&atid=114534">our bugtracker</a>.
  <p>
  <ul>
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b1.tar.gz">source archive</a></li>
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b1-macosx10.2.dmg">binary installer for Mac OS X 10.2 (Python 2.2)</a></li>
    <li><a href="<? print $root; ?>prerelease/pyobjc-1.1b1-macosx10.3.dmg">binary installer for Mac OS X 10.3 (Python 2.3)</a></li>
    <li><a href="<? print $root; ?>packman/pyobjc-unstable-macosx10.2.plist">PackMan Database for MacOS X 10.2 (MacPython 2.3)</a></li>
    <li><a href="<? print $root; ?>packman/pyobjc-unstable-macosx10.3.plist">PackMan Database for MacOS X 10.3 (Python 2.3)</a></li>
  </ul>
  <p>
<b>NOTE: </b>Python 2.2 support is tested less than Python 2.3 support, because
most developers have moved to Mac OS X 10.3.
  <p>

<span class="news_date">2004-02-02: </span><span class="news_headline">PyObjC 1.1a0 released</span><?php gray_line(); ?>
  <p>
A prerelease of the upcoming 1.1 release of PyObjC is available. This version 
contains numereous improvements, especially when you're using PyObjC on Panther.
See the <a href="<? print $root; ?>NEWS-1.1.txt">NEWS file</a> for details.
  <p>
There currently is no binary installer for Mac OS X 10.2, that will be made
available with the next release.


<span class="news_date">2003-10-08: </span><span class="news_headline">PyObjC 1.0 released</span><?php gray_line(); ?>
  <p>
We're happy to announce the release of PyObjC 1.0. This version fixes the bugs 
found in the last beta and adds support for Key-Value Coding, see the 
<a href="<? print $root; ?>NEWS-1.0.txt">NEWS file</a> for details.
  <p>
A disk image and the sources are <a href="http://sourceforge.net/project/showfiles.php?group_id=14534">available</a>.  Users of <? print $macpython23 ?> can install 
PyObjC using the Package Manager.
  <p>
<span class="news_date">2003-07-05: </span><span class="news_headline">PyObjC 1.0b1 released</span><?php gray_line(); ?>
  <p>
 PyObjC 1.0b1 has shipped. A disk image with an installer package and the 
 sources are <a href="http://sourceforge.net/project/showfiles.php?group_id=14534">available</a>. There are many new features and bugfixes, see the 
 <a href="<? print $root; ?>NEWS-1.0b1.txt">NEWS file</a> for details. The improvements include:
 <p>
 <ul>
 <li> Improved performance and stability
 <li> Better tutorials and examples
 <li> Initial support for MacOS X 10.1
 <li> Support for the WebKit framework
 <li> Write plugin bundles in Python (requires Python 2.3)
 </ul>
 <p>
 The PyObjC installer package installs the Python packages for use with the 
 Apple provided Python 2.2 on MacOS X 10.2 as well as a number of project
 builder templates.  Users of <? print $macpython23 ?> can install this release using the 
 PackageManager application.

<p><span class="news_date">2003-07-05: </span><span class="news_headline">CVS snapshots</span><?php gray_line(); ?>
  <P>
We now have CVS snapshots available <a href="/cvs-snapshots">here</a>. These
are automaticly generated snapshots of our CVS tree. They might not work, and
need not even compile. 
<p><span class="news_date">2003-05-07: </span><span class="news_headline">Updated tutorial</span><?php gray_line(); ?>
  <p>
The tutorial included in the 0.9 release was not entirely up-to-date, please use <a href="<? print $root; ?> doc/tutorial.php">the tutorial on this website</a>.
<p>
<span class="news_date">2003-05-02: </span><span class="news_headline">PyObjC 0.9 released</span><?php gray_line(); ?>
 <p>
 PyObjC 0.9 has shipped. A disk image with an installer package and the sources are <a href="http://sourceforge.net/project/showfiles.php?group_id=14534">available</a>. There are many new features and bugfixes, see the <a href="<? print $root; ?>NEWS-1.0.txt">NEWS file</a> for details.
 <p>
 The PyObjC installer package installs a number of examples and project builder
 templates as wel as documentation into /Developer. Users of 
 <a href="http://homepages.cwi.nl/~jack/macpython.html#beta">MacPython 2.3b1</a> can install this release using the 
 PackageManager application.
 <p>
<p><span class="news_date">2003-01-23: </span><span class="news_headline">Dev News; GNUstep support, FFI, performance, etc...</span><?php gray_line(); ?>
<p>
<span class="news_date">2002-12-19: </span><span class="news_headline">PyObjC 0.8 released</span><?php gray_line(); ?>
PyObjC v0.8 has finally shipped!  A disk image and source tarball are <a href="http://sourceforge.net/project/showfiles.php?group_id=14534">now available</a>.  The PyObjC installer package now contains Examples that are installed into /Developer/Examples/PyObjC.</p><p>There are many new features and bug fixes found within this release.  Please see the <a href="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/pyobjc/pyobjc/ChangeLog?rev=1.58&only_with_tag=REL_20021219_0pt8&content-type=text/vnd.viewcvs-markup">ChangeLog</a> for details.  Documentation is still lacking.  It will be improved in the next release.</p>
<span class="news_date">2002-11-22: </span><span class="news_headline">CVS commit notificaiton mailing list available</span><?php gray_line(); ?>
  <p>
A <a href="http://lists.sourceforge.net/mailman/listinfo/pyobjc-checkins">mailing list</a> has been created to which all CVS commit notifications will be automatically posted.   Each message includes both the file(s) changed and diff-style output of exactly what changed.
</p>
<span class="news_date">2002-11-12: </span><span class="news_headline">Initial release of web site</span><?php gray_line(); ?>
  <p>
For the first time ever, the PyObjC module has a real web site (the start of one anyway).  The implementation is largely a copy of the <a href="http://fink.sourceforge.net/">Fink project's excellent site.</a>.  The design and graphics were contributed by <a href="http://starship.python.net/crew/jwt/">Jim Tittsler</a>.  The content was compiled from many sources-- Jim's work, Fink, the PyObjC source trees and some original-- by <a href="http://radio.weblogs.com/0100490/">Bill Bumgarner</a>.
</p>
<span class="news_date">2002-10-13: </span><span class="news_headline">Interim release 0.7.0</span><?php gray_line(); ?>
  <p> On or about this date, an interim release of PyObjC was made available as a disk image that contained the binary module (compatible with Apple's build of Python included with OS X 10.2), a Project Builder project template for building Cocoa applications using Python, and a basic README.</p>
  <p>Version 0.7.0 represents a huge step forward over the previous version (0.6.1).  Of note, 0.7.0 vastly improved the inter-language messaging mechanism, the bridging of various classes, improved support for features specific to the Foundation and AppKit, support for the Address Book framework, and subclassing of Objective-C classes in Python.</p>
<span class="news_date">2002-01-30: </span><span class="news_headline">Release 0.6.1</span><?php gray_line(); ?>
<p>
Last release made that used a single dynamically loadable module named 'pyobjc'.
</p>
