#!/bin/sh

# Make sure 0.8 and 0.7 are removed completely.  In the future,
# the package will auto update previous versions.

rm -rf "/Developer/ProjectBuilder Extras/Project Templates/Application/Cocoa-Python Application"

rm -rf "/Developer/Examples/PyObjC"

rm -rf "/Library/Receipts/PyObjC-0.8.pkg"

# Versions of PyObjC before 0.9 installed python files in the site-packages
# directory, from 0.9 onwards we install in site-packages/PyObjC.

for dn in AddressBook AppKit Foundation autoGil.so objc
do
	rm -rf "/usr/lib/python2.2/site-packages/${dn}"
done

exit 0
