/*
 * This file is generated by objective.metadata
 *
 * Last update: Mon Aug 10 09:56:10 2015
 */

#if PyObjC_BUILD_RELEASE >= 1007
#import <QTKit/QTExportSession.h>
#endif

static void __attribute__((__used__)) use_protocols(void)
{
    PyObject* p __attribute__((__unused__));
#if PyObjC_BUILD_RELEASE >= 1007
    p = PyObjC_IdToPython(@protocol(QTExportSessionDelegate)); Py_XDECREF(p);
#endif
}
