import AutomaticAssessmentConfiguration
import objc
from PyObjCTools.TestSupport import TestCase, min_os_level


class TestAEAssessmentConfiguration(TestCase):
    @min_os_level("10.15.4")
    def test_classes(self):
        self.assertIsInstance(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration, objc.objc_class
        )

    @min_os_level("26.1")
    def test_methods26_1(self):
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityKeyboard
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityKeyboard_,
            0,
        )

        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityLiveCaptions
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityLiveCaptions_,
            0,
        )

        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityReader
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityReader_,
            0,
        )

    @min_os_level("27.0")
    def test_methods27_0(self):
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsDictation
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsDictation_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityAlternativeInputMethods
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityAlternativeInputMethods_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityBackgroundSounds
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityBackgroundSounds_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityHoverText
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityHoverText_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityLiveSpeech
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityLiveSpeech_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilitySpokenContent
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilitySpokenContent_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilitySwitchControl
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilitySwitchControl_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityVoiceControl
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityVoiceControl_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityVoiceOver
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityVoiceOver_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAccessibilityZoom
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAccessibilityZoom_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsEmojiKeyboard
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsEmojiKeyboard,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsUserScriptExecution
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsUserScriptExecution,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsAutoFill
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsAutoFill_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsStructuralInput
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsStructuralInput_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsDock
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsDock_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowsMenuBar
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowsMenuBar_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowOnlyParticipantsToRun
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowOnlyParticipantsToRun_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowLockdownMode
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowLockdownMode_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.allowPrivateRelay
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setAllowPrivateRelay_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.requiresManagedDevice
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setRequiresManagedDevice_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.requiresSIP
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setRequiresSIP_,
            0,
        )
        self.assertResultIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.requiresSingleUser
        )
        self.assertArgIsBOOL(
            AutomaticAssessmentConfiguration.AEAssessmentConfiguration.setRequiresSingleUser_,
            0,
        )
