"""
Python mapping for the Cocoa AppKit.

This module does not contain docstrings for the wrapped code, check Apple's
documentation for details on how to use these functions and classes.
"""
import _AppKitSignatures 
import objc as _objc

# We first register special methods signatures with the runtime. The module
# is not used for anything else.

from _AppKit import *

CLASSLIST=[
	"NSGrayFrame",
	"NSPopUpButton",
	"NSPPDParse",
	"NSMenuArrowView",
	"_NSDIBPboardTypeConverter",
	"NSGlyphHole",
	"NSImageWriter",
	"NSDirInfoSerializer",
	"NSCStringText",
	"NSPrintInfoAttributeDictionary",
	"NSMenu",
	"NSFocusState",
	"NSHelpAttachment",
	"NSAccessibilityProxy",
	"NSImageCell",
	"NSSurface",
	"NSInputManager",
	"_NSFilePromiseTypeConverter",
	"NSGreySliders",
	"NSMutableParagraphStyle",
	"NSFileWrapper",
	"NSTableHeaderCell",
	"_NSToolbarItemViewerLabelCellPopUpCellProxy",
	"NSAccessibilityNotifier",
	"NSFontManager",
	"NSServicesPasteboard",
	"NSCarbonMenuImpl",
	"NSStorage",
	"NSDisclosureButtonCell",
	"NSFileLocator",
	"NSTableColumn",
	"NSToolbar",
	"NSFlippableView",
	"NSViewTextAttachmentCellHelper",
	"NSColorPanelColorWell",
	"NSJPEGImageReader",
	"NSOutlineView",
	"NSToolbarPoofAnimator",
	"NSJPEGImageWriter",
	"NSViewRectCache",
	"NSTSMInputContext",
	"NSNewFolderPanel",
	"_NSColorPanelToolbarItem",
	"_NSPICTPboardTypeConverter",
	"NSDeadKeyInputServer",
	"NSPageData",
	"NSRulebookSetObject",
	"NSTextStorage",
	"NSAttachmentTextStorage",
	"NSExceptionHandlingRecursiveLock",
	"NSScrollView",
	"_NSToolbarButtonCell",
	"_NSDragManager",
	"NSInputContext",
	"NSKeyBindingManager",
	"NSEvent",
	"_NSPDFPboardTypeConverter",
	"NSPersistentGraphicsContext",
	"NSMouseTracker",
	"_NSMovieUndoOperation",
	"NSSliderCell",
	"NSAKDeserializer",
	"NSCarbonWindow",
	"NSConcreteTextStorage",
	"NSPSMatrix",
	"NSIdentityGlyphInfo",
	"NSFocusStack",
	"NSControl",
	"NSRulerView",
	"NSLocalInputServer",
	"NSHFSObject",
	"NSStepper",
	"NSHFSBrowserCell",
	"NSGradientPatternColor",
	"NSDPSContext",
	"_NSToolbarImageRepView",
	"NSConcreteGlyphGenerator",
	"_NSFileNameFormatter",
	"NSMoveHelper",
	"NSImageRep",
	"NSCoreDragManager",
	"NSSlider",
	"NSWindowGraphicsContext",
	"NSViewHierarchyLock",
	"NSProgressIndicator",
	"NSFontPanelPreviewSplitView",
	"NSThemeTearOffFrame",
	"NSLanguage",
	"_NSStringPboardTypeConverter",
	"NSObsoleteBitmap",
	"_NSTIFFPboardTypeConverter",
	"NSFormCell",
	"_NSAsciiPboardTypeConverter",
	"NSToolbarSeparatorItem",
	"NSHyphenator",
	"NSButton",
	"NSLayoutHole",
	"NSDefaultSpellServerDelegate",
	"NSDocumentDragButton",
	"NSToolTipPanel",
	"NSComboBoxWindow",
	"NSRulebook",
	"_NSContextHelpBorderView",
	"NSPrinter",
	"NSSecureTextField",
	"NSOpenGLPixelFormat",
	"NSBrowserCell",
	"NSCachedImageRep",
	"NSButtonCell",
	"NSTextAttachment",
	"NSGIFImageReader",
	"NSGIFImageWriter",
	"NSFontPanelPreview",
	"NSToolbarView",
	"NSColorPickerUserView",
	"NSTextField",
	"NSFrameView",
	"NSAccessibilityMockUIElement",
	"_NSCornerView",
	"NSAKSerializerStream",
	"NSAttributeDictionary",
	"NSServiceListener",
	"NSMenuItemCell",
	"NSGraphicsContext",
	"NSQuickDrawView",
	"NSMenuItem",
	"NSWindowController",
	"NSView",
	"NSBezierPath",
	"NSFontPanel",
	"NSColorPickerCrayon",
	"NSAlert",
	"NSPICTStream",
	"NSFileSpecifier",
	"NSPDFImageRep",
	"NSSystemInfoPanel",
	"NSPrintInfo",
	"NSColorPanelResizeDimple",
	"NSCatalogColor",
	"NSTextViewSharedData",
	"NSCollatorElement",
	"NSAccessibilityStepperArrowButton",
	"NSCalibratedRGBColor",
	"NSCustomImageRep",
	"_NSSparseArrayEnumeration",
	"NSSavePanel",
	"NSColorScaleSliderCell",
	"_NSToolbarItemViewerLabelCellPopUpCell",
	"NSBMPImageReader",
	"NSIncrementalImageReader",
	"NSRTFWriter",
	"NSPageLayout",
	"NSBitmapImageRep",
	"NSHSBSliders",
	"NSCollator",
	"NSColor",
	"NSAppleMenuItemRepresentedObject",
	"NSToolbarFlexibleSpaceItem",
	"NSFont",
	"_PanelLoader",
	"NSTabWell",
	"NSTextView",
	"NSColorPickerWheelView",
	"NSWorkspace",
	"NSThemeFrame",
	"NSSortedArray",
	"NSIBObjectData",
	"NSStringDrawingTextStorage",
	"_NSMagnifier",
	"_NSPeriodicEventSource",
	"_NSColorPboardTypeConverter",
	"NSDocument",
	"NSFilePromiseDragSource",
	"NSColorPanel",
	"NSColorPickerWheel",
	"NSPopUpButtonCell",
	"NSMenuPanel",
	"_NSToolbarSeparator",
	"NSServiceMaster",
	"_NSFlippedImage",
	"NSOutlineRow",
	"NSAffineTransform",
	"NSCompressedSimpleCollatorElement",
	"NSSimpleNumberFormatter",
	"NSLeafProxy",
	"NSTitledFrame",
	"_NSViewGState",
	"NSPasteboard",
	"NSTableRow",
	"NSMovieViewTextAttachmentCell",
	"NSWindow",
	"NSBinaryCollatorElement",
	"NSAccessibilityScrollerPart",
	"NSImageViewTextAttachmentCell",
	"NSComboBox",
	"_NSAttributes",
	"NSDeviceRGBColor",
	"NSMovieView",
	"NSFontPanelScrollView",
	"NSDrawerFrame",
	"NSTracer",
	"NSTypesetter",
	"NSInputClientWrapper",
	"NSKeyBindingAtom",
	"NSATSTypesetter",
	"NSComboBoxCell",
	"NSToolbarSpaceItem",
	"NSMultipassCollatorElement",
	"NSCrayon",
	"NSHFSiDiskObject",
	"NSPanelController",
	"NSCMYKSliders",
	"_NSThemeCloseWidgetCell",
	"_NSThemeWidget",
	"NSRTFD",
	"NSSavePanelFormCell",
	"NSTableView",
	"NSCharacterProperty",
	"NSDirInfo",
	"NSCustomView",
	"NSStopTouchingMeBox",
	"NSToolbarClippedItemsIndicator",
	"NSColorList",
	"NSUIHeartBeat",
	"NSButtonImageSource",
	"NSDrawerWindow",
	"NSImage",
	"NSSecureTextFieldCell",
	"NSImageReader",
	"NSCIDGlyphInfo",
	"NSTabViewItem",
	"NSPreferencesModule",
	"NSQTImageImporter",
	"NSMultipassCollatorState",
	"NSEPSImageRep",
	"_NSThemeWidgetCell",
	"NSRulerMarker",
	"NSCursor",
	"NSScreen",
	"NSNibConnector",
	"NSCell",
	"NSGlyphNameGlyphInfo",
	"NSNoBranchIconBrowserCell",
	"NSConcreteNotifyingMutableAttributedString",
	"NSRulebookCharacterSet",
	"NSIBHelpConnector",
	"NSCompressedMultipassCollatorElement",
	"_NSKeyboardFocusClipView",
	"_NSDrawingThreadData",
	"_NSFocusStackElement",
	"NSUndoTextOperation",
	"NSRulerMarkerPanel",
	"NSAppleMenuController",
	"NSProgressPanel",
	"NSSplitView",
	"NSMenuTemplate",
	"__NSEventDiscardInfo",
	"NSKitPanelController",
	"NSPSAndPDFGraphicsContext",
	"NSTabView",
	"NSSystemStatusBar",
	"NSQuickDrawPort",
	"NSUndoSetAttributes",
	"NSToolbarButton",
	"_NSPDFDocument",
	"NSPreferences",
	"NSDPSServerContext",
	"NSGlyphInfo",
	"NSLayoutManager",
	"NSRemoteInputServer",
	"NSOpenPanel",
	"_NSCGFontCharacterSet",
	"NSStatusBarButtonCell",
	"NSDeviceWhiteColor",
	"_NSPromiseContentsTypeConverter",
	"_NSQDCGSContext",
	"NSPICTImageRep",
	"NSAccessibilityWindowGrowBox",
	"NSPrintOperation",
	"NSSecureTextStorage",
	"NSLineHeightFormatter",
	"NSRunStorage",
	"NSStatusBarWindow",
	"NSColorPickerList",
	"NSPanel",
	"NSMenuView",
	"NSICOImageReader",
	"NSSimpleHorizontalTypesetter",
	"_NSFilenamePboardTypeConverter",
	"_NSURLPboardTypeConverter",
	"NSDirInfoDeserializer",
	"NSTextTemplate",
	"NSHFSContainer",
	"NXTypesPair",
	"NSOpenGLContext",
	"NSToolbarItemViewer",
	"_NSSavePanelForm",
	"NSATSGlyphGenerator",
	"NSLazyBrowserCell",
	"NSTempAttributeDictionary",
	"NSClassSwapper",
	"NSSpellChecker",
	"NSActionCell",
	"NSBox",
	"NSUnavailableLanguagePlaceholder",
	"NSTextViewTemplate",
	"NSDocInfo",
	"NSToolTipManager",
	"NSMatrix",
	"NSPNGImageReader",
	"NSPNGImageWriter",
	"NSTextAttachmentMovieView",
	"NSAKSerializer",
	"NSDeviceCMYKColor",
	"NSColorHolder",
	"NSParagraphStyle",
	"NSTiogaGraphicsContext",
	"NSSplitViewSplitter",
	"NSViewTextAttachmentCell",
	"NSClipView",
	"NSCustomResource",
	"_NSThemeCloseWidget",
	"_NSColorPanelToolbar",
	"NSCustomObject",
	"NSDocumentSerializer",
	"NSColorSwatch",
	"_NSAttributeRun",
	"NSDocumentController",
	"_NSToolbarItemPlaceholder",
	"NSFontPanelMatrix",
	"NSStepperCell",
	"NSNibControlConnector",
	"NSNSPrintInfoAttributeKeyEnumerator",
	"NSDynamicSystemColor",
	"NSColorWell",
	"NSImageView",
	"NSFileDragSource",
	"NSQueryText",
	"NSToolTip",
	"NSTableHeaderView",
	"NSCachedWhiteColor",
	"_NSButtonImage",
	"NSHFSIndirectObject",
	"NSColorScaleSlider",
	"NSScrollingMatrix",
	"NSStringDrawingContext",
	"NSText",
	"NSCarbonWindowFrame",
	"NSSavePanelBox",
	"NSCachedRGBColor",
	"_NSToolbarItemViewerLabelCell",
	"NSRTFReader",
	"NSMenuScrollView",
	"NSBMPImageWriter",
	"NSColorPickerSliders",
	"_NSSparseArray",
	"NSUndoReplaceCharacters",
	"NSBulletString",
	"NSToolbarItem",
	"NSForm",
	"NSAccessibilityReparentingCellProxy",
	"_NSToolbarFlexibleSpace",
	"NSServicesMenuHandler",
	"NSPatternColor",
	"NSScroller",
	"NSConcretePrintOperation",
	"NSAKDeserializerStream",
	"NSColorSpaceSliders",
	"NSTextFieldCell",
	"NSViewTemplate",
	"NSAcceptsColorBrowser",
	"NSRGBSliders",
	"NSNextStepFrame",
	"NSThemeDocumentButton",
	"NSHelpManager",
	"NSPrintPanel",
	"NSDragDestination",
	"_NSPboardTypeConverter",
	"NSColorPicker",
	"NSComboTableView",
	"NSTextAttachmentCell",
	"NSAttributeDictionaryEnumerator",
	"NSBrowser",
	"NSTableViewCellProxy",
	"NSOpenGLView",
	"NSTextContainer",
	"NSColorPanelTextController",
	"NSMovie",
	"NSStatusBar",
	"NSApplication",
	"NSDocumentDeserializer",
	"NSPICTParser",
	"_NSToolbarViewClipView",
	"NSCarbonWindowContentView",
	"NSWindowTemplate",
	"NSCalibratedWhiteColor",
	"NSCrayonRow",
	"NSSound",
	"NSDrawer",
	"NSLazyBrowserList",
	"NSAccessibilityReparentingProxy",
	"NSCGSFont",
	"NSColorPickerUser",
	"NSInputServer",
	"NSUndoTyping",
	"_NSToolbarClippedItemsIndicatorCell",
	"NSGraphicCell",
	"NSNibOutletConnector",
	"_NSRTFPboardTypeConverter",
	"NSWorkspaceCenter",
	"NSTabletEvent",
	"NSGlyphGenerator",
	"NSCGSContext",
	"NSColorPickerCrayonView",
	"NSPrivateKitClassForFindingBundle",
	"NSStatusBarButton",
	"NSHardLinkInfo",
	"NSStatusItem",
	"_NSToolbarSpace",
	"NSTearOffFrame",
	"NSThemeDocumentButtonCell",
	"NSSecureTextView",
	"NSSubTextStorage",
	"NSToolbarConfigPanel",
	"NSScriptMenu",
	"NSResponder",
	"NSTextTab",
	"NSComboBoxButtonCell",
]


# We try to import a module containing support code, the code
# is only ever used from the C side.
import _AppKitMapping 

# Load the Cocoa bundle, and gather all classes defined there
import Foundation
Foundation._objc.loadBundle("AppKit", globals(), bundle_path="/System/Library/Frameworks/AppKit.framework", bundle_classes=CLASSLIST)
del CLASSLIST
Foundation._objc.recycle_autorelease_pool()
del Foundation


# Define usefull utility methods here
NSClassForName = _objc.lookUpClass


def NSEndSheetMethod(meth):
    """
    Return a selector that can be used as the delegate callback for
    sheet methods
    """
    return _objc.selector(meth, signature='v@:@@i')

def NSMakePoint(p1, p2):
    return (float(p1), float(p2))

def NSMakeSize(h, w):
    return (float(h), float(w))

def NSMakeRect(p1, p2, h, w):
    return ((p1, p2), (h, w))

import protocols  # no need to export these, just register with PyObjC

#
# (informal) protocols eported for b/w compatibility
#
from protocols import NSAccessibility, NSChangeSpelling, NSColorPickingCustom, \
                       NSColorPickingDefault, NSComboBoxCellDataSource, NSComboBoxDataSource, \
                       NSDraggingDestination, NSDraggingInfo, NSDraggingSource, \
                       NSIgnoreMisspelledWords, NSInputServerMouseTracker, NSMenuValidation, \
                       NSOutlineViewDelegate, NSOutlineViewDataSource, NSServicesRequests, \
                       NSTableViewDelegate, NSTableDataSource, NSToolTipOwner, \
                       NSToolbarItemValidation, NSToolbarDelegate, NSUserInterfaceValidations, \
                       NSValidatedUserInterfaceItem, NSApplicationDelegate, NSTextViewDelegate
