
/*
 *     *** GENERATED FILE ***
 *
 * This file is generated by Tools/generate-category-tests.py
 */
#include "Python.h"
#include "pyobjc-api.h"

#import <Foundation/Foundation.h>
__attribute__((__visibility__("default")))
@interface OC_Category_GP42 : NSObject {
}
@end

__attribute__((__visibility__("default")))
@interface OC_Category_P42 : OC_Category_GP42 {
}
@end

__attribute__((__visibility__("default")))
@interface OC_Category_C42 : OC_Category_P42 {
}
@end

@implementation
OC_Category_C42 (Cat)
- (id)gpMethod1
{
    return @"C42 - gpMethod1 - C42(Cat)";
}
- (id)gpMethod5
{
    return @"C42 - gpMethod5 - C42(Cat)";
}
- (id)pMethod1
{
    return @"C42 - pMethod1 - C42(Cat)";
}
- (id)pMethod3
{
    return @"C42 - pMethod3 - C42(Cat)";
}
- (id)method1
{
    return @"C42 - method1 - C42(Cat)";
}
- (id)method2
{
    return @"C42 - method2 - C42(Cat)";
}
@end

static PyMethodDef mod_methods[] = {{0, 0, 0, 0}};

static struct PyModuleDef mod_module = {
    PyModuleDef_HEAD_INIT, "category_c42", NULL, 0, mod_methods, NULL, NULL, NULL, NULL};

PyObject* PyInit_category_c42(void);

PyObject* __attribute__((__visibility__("default"))) PyInit_category_c42(void)
{
    PyObject* m;

    m = PyModule_Create(&mod_module);
    if (!m) {
        return NULL;
    }

    PyObjC_ImportAPI(m);

    return m;
}
