
/*
 *     *** GENERATED FILE ***
 *
 * This file is generated by Tools/generate-category-tests.py
 */
#include "Python.h"
#include "pyobjc-api.h"

#import <Foundation/Foundation.h>
__attribute__((__visibility__("default")))
@interface OC_Category_GP31 : NSObject {
}
@end

__attribute__((__visibility__("default")))
@interface OC_Category_P31 : OC_Category_GP31 {
}
@end

__attribute__((__visibility__("default")))
@interface OC_Category_C31 : OC_Category_P31 {
}
@end

@implementation
OC_Category_P31 (Cat)
- (id)gpMethod1
{
    return @"P31 - gpMethod1 - P31(Cat)";
}
- (id)gpMethod5
{
    return @"P31 - gpMethod5 - P31(Cat)";
}
- (id)pMethod1
{
    return @"P31 - pMethod1 - P31(Cat)";
}
- (id)pMethod3
{
    return @"P31 - pMethod3 - P31(Cat)";
}
- (id)method1
{
    return @"P31 - method1 - P31(Cat)";
}
- (id)method2
{
    return @"P31 - method2 - P31(Cat)";
}
@end

static PyMethodDef mod_methods[] = {{0, 0, 0, 0}};

static struct PyModuleDef mod_module = {
    PyModuleDef_HEAD_INIT, "category_p31", NULL, 0, mod_methods, NULL, NULL, NULL, NULL};

PyObject* PyInit_category_p31(void);

PyObject* __attribute__((__visibility__("default"))) PyInit_category_p31(void)
{
    PyObject* m;

    m = PyModule_Create(&mod_module);
    if (!m) {
        return NULL;
    }

    PyObjC_ImportAPI(m);

    return m;
}
