import sys

import Cocoa

# import DataProvidersAndConsumers
import Images
import Quartz
import Utilities


def exportImageWithMaskFromURLWithDestination(
    context,
    imageURL,
    imagewidth,
    imageheight,
    bitsPerComponent,
    theMaskingImageURL,
    maskwidth,
    maskheight,
):

    imageBitsPerPixel = bitsPerComponent * 3
    bytesPerRow = ((imagewidth * imageBitsPerPixel) + 7) / 8
    shouldInterpolate = True
    imageDataProvider = Quartz.CGDataProviderCreateWithURL(imageURL)
    if imageDataProvider is None:
        print("Couldn't create Image Data provider!")
        return

    colorspace = Utilities.getTheCalibratedRGBColorSpace()
    image = Quartz.CGImageCreate(
        imagewidth,
        imageheight,
        bitsPerComponent,
        imageBitsPerPixel,
        bytesPerRow,
        colorspace,
        Quartz.kCGImageAlphaNone,
        imageDataProvider,
        None,
        shouldInterpolate,
        Quartz.kCGRenderingIntentDefault,
    )
    del imageDataProvider
    if image is None:
        print("Couldn't create CGImageRef for this data!")
        return

    imageRect = Quartz.CGRectMake(0.0, imageheight, imagewidth, imageheight)
    # Draw the image.
    Quartz.CGContextDrawImage(context, imageRect, image)

    # Now the mask.
    maskDataProvider = Quartz.CGDataProviderCreateWithURL(theMaskingImageURL)
    if maskDataProvider is None:
        print("Couldn't create Image Data provider!")
        return

    mask = Quartz.CGImageMaskCreate(
        maskwidth,
        maskheight,
        bitsPerComponent,
        bitsPerComponent,
        maskwidth,
        maskDataProvider,
        None,
        shouldInterpolate,
    )
    del maskDataProvider
    if mask is None:
        print("Couldn't create CGImageRef for mask data!")
        return

    # Draw the mask below the image.
    maskRect = Quartz.CGRectMake(0.0, 0.0, maskwidth, maskheight)
    Quartz.CGContextDrawImage(context, maskRect, mask)

    # Create a new CGImage object, the image, masked with mask.
    imageMaskedWithImage = Quartz.CGImageCreateWithMask(image, mask)
    # Once the new image is created, we can release the image
    # and the mask which make it up. Quartz retains what it needs
    # for the new masked image.
    del image
    del mask

    if imageMaskedWithImage is None:
        print("Couldn't create image masked with mask!")
        return

    imageRect = Quartz.CGRectMake(imagewidth, imageheight / 2, imagewidth, imageheight)
    # Draw the masked image to the right of the image and its mask.
    Quartz.CGContextDrawImage(context, imageRect, imageMaskedWithImage)

    # Of course this is a total hack.
    outPath = b"/tmp/imageout.png"
    exportURL = Cocoa.CFURLCreateFromFileSystemRepresentation(
        None, outPath, len(outPath), False
    )

    if exportURL is not None:
        Images.exportCGImageToPNGFileWithDestination(imageMaskedWithImage, exportURL)


if sys.version_info[0] == 2:

    def make_bytes(values):
        return "".join(map(chr, values))


else:

    def make_bytes(values):
        return bytes(values)


_data = make_bytes(
    (
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0xf8,
        0xe7,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x00,
        0x40,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x06,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x01,
        0xc0,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x0f,
        0xf8,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x0f,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xfc,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xfc,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x00,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x03,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x03,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0x80,
        0x01,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xfe,
        0x40,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x05,
        0xef,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x3f,
        0x00,
        0x03,
        0xfc,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x7c,
        0x00,
        0x00,
        0x78,
        0x1f,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x38,
        0x00,
        0x00,
        0x78,
        0x3c,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x78,
        0x00,
        0x00,
        0x70,
        0x18,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x78,
        0x1f,
        0x00,
        0x30,
        0x00,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x7c,
        0x3f,
        0x00,
        0x18,
        0x00,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x38,
        0x00,
        0x00,
        0x03,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x80,
        0x00,
        0x3c,
        0x00,
        0x0c,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x3c,
        0x20,
        0x1c,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x04,
        0x00,
        0x3c,
        0x00,
        0x3c,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x70,
        0xbf,
        0x86,
        0x3c,
        0x1f,
        0xfc,
        0x0b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xa0,
        0x11,
        0xf0,
        0x0e,
        0x3c,
        0x1f,
        0xfe,
        0x8b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xa0,
        0x19,
        0xf0,
        0x0c,
        0x3c,
        0x0f,
        0xff,
        0x0b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xb0,
        0x1d,
        0xfe,
        0x1c,
        0x7e,
        0x0f,
        0xff,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xb8,
        0x1c,
        0xff,
        0x3c,
        0xfe,
        0x03,
        0xfe,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x1e,
        0x7f,
        0xf8,
        0xde,
        0x00,
        0x7c,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x1e,
        0x7f,
        0xf1,
        0xdf,
        0x30,
        0x03,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x1f,
        0x3f,
        0xe3,
        0x9f,
        0x10,
        0x3f,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x0f,
        0xff,
        0x83,
        0xdf,
        0x80,
        0x1f,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x03,
        0xfc,
        0x03,
        0xdf,
        0x81,
        0x8f,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x07,
        0xfe,
        0x1f,
        0x8f,
        0x00,
        0x07,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x07,
        0xfe,
        0x3c,
        0x06,
        0x00,
        0x01,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x03,
        0xfc,
        0x7c,
        0x00,
        0x00,
        0x01,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x01,
        0xf8,
        0x7f,
        0x00,
        0x00,
        0x01,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x01,
        0xf8,
        0xff,
        0xe0,
        0x30,
        0x01,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0xf1,
        0xef,
        0xf9,
        0xe0,
        0x03,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x80,
        0xf1,
        0xff,
        0xff,
        0x80,
        0x0f,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x03,
        0xe2,
        0xff,
        0xfe,
        0x00,
        0x1f,
        0x87,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x83,
        0xf0,
        0x00,
        0x00,
        0x1c,
        0x3f,
        0x87,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc3,
        0xf0,
        0x00,
        0x01,
        0xf8,
        0x0f,
        0x87,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc3,
        0xf0,
        0x03,
        0xff,
        0xf0,
        0x5f,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc1,
        0xff,
        0xc7,
        0xff,
        0xe0,
        0x7f,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe1,
        0xff,
        0xf1,
        0xff,
        0x80,
        0x2f,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe1,
        0xff,
        0xf8,
        0x0f,
        0xc0,
        0x06,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf4,
        0xff,
        0xfe,
        0x0f,
        0xf8,
        0x44,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf4,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x64,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf9,
        0xff,
        0xff,
        0xff,
        0x3c,
        0xe4,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfd,
        0x9f,
        0xff,
        0xfc,
        0x1f,
        0xc0,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfd,
        0x1f,
        0xff,
        0xfc,
        0x03,
        0xc0,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x01,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0xff,
        0xff,
        0xff,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0xff,
        0xff,
        0xff,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x80,
        0x7f,
        0xff,
        0xff,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x80,
        0x1f,
        0xff,
        0xff,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0xc0,
        0x0f,
        0xff,
        0xff,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x07,
        0xff,
        0xff,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x03,
        0xff,
        0xff,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x70,
        0x01,
        0xff,
        0xfc,
        0x00,
        0x17,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x78,
        0x00,
        0x7f,
        0xf0,
        0x00,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0xfc,
        0x00,
        0x00,
        0x00,
        0x00,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x03,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x1f,
        0xff,
        0x80,
        0x00,
        0x00,
        0x00,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x7f,
        0x7f,
        0xc0,
        0x00,
        0x00,
        0x00,
        0x07,
        0xff,
        0xff,
    )
)


def getMaskData1():
    return _data


_data2 = make_bytes(
    (
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0x00,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x00,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x00,
        0x01,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x00,
        0x00,
        0x00,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x00,
        0x01,
        0x80,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x00,
        0x03,
        0xc0,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x00,
        0x0b,
        0xe0,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x00,
        0x07,
        0xf0,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xf4,
        0x83,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xe4,
        0x03,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xe4,
        0x43,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xe4,
        0x4b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x00,
        0x02,
        0xff,
        0xe4,
        0x5b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x02,
        0xff,
        0xe0,
        0x5b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x07,
        0xc1,
        0xff,
        0xe0,
        0x59,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x18,
        0x00,
        0x7f,
        0xf0,
        0xfe,
        0x00,
        0x79,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x18,
        0x00,
        0x78,
        0x0f,
        0xfe,
        0x04,
        0xe1,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x18,
        0x00,
        0xb0,
        0x47,
        0xff,
        0xff,
        0xe1,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x10,
        0x00,
        0xc4,
        0x69,
        0xff,
        0xff,
        0xc3,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfe,
        0x10,
        0x01,
        0xff,
        0xe1,
        0xfc,
        0x07,
        0xc1,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x01,
        0xff,
        0xf8,
        0x78,
        0x01,
        0xc5,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x04,
        0x01,
        0xff,
        0xf0,
        0x78,
        0x01,
        0xc5,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x0c,
        0x00,
        0xff,
        0xf8,
        0x7e,
        0x3f,
        0xc1,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x0c,
        0x00,
        0x7f,
        0xf0,
        0x18,
        0xff,
        0xc3,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x07,
        0x00,
        0x7f,
        0xf4,
        0x1f,
        0xff,
        0xe3,
        0xff,
        0xff,
        0xff,
        0xff,
        0xfc,
        0x23,
        0x00,
        0x7f,
        0xe0,
        0x3e,
        0xff,
        0xe3,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x11,
        0x00,
        0x7f,
        0xec,
        0x5f,
        0xbf,
        0xe3,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x01,
        0x00,
        0x3f,
        0xce,
        0x7e,
        0x3f,
        0xe3,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x08,
        0x00,
        0x7f,
        0x80,
        0x2e,
        0x3f,
        0xe3,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf8,
        0x06,
        0x00,
        0x7f,
        0x00,
        0x6e,
        0x3f,
        0xeb,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x7e,
        0x0d,
        0xfe,
        0xff,
        0xeb,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x3c,
        0x00,
        0xfe,
        0x3f,
        0xeb,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x50,
        0x00,
        0xfe,
        0x3f,
        0xcb,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x01,
        0x98,
        0xff,
        0x3f,
        0xcb,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0xc7,
        0xe1,
        0xff,
        0x3f,
        0x8b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x40,
        0xff,
        0xff,
        0xbf,
        0x8b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0xe0,
        0x1f,
        0xff,
        0xdf,
        0x0b,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0xe8,
        0x63,
        0xff,
        0xdf,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x02,
        0xfc,
        0xf9,
        0xff,
        0xef,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x03,
        0xfe,
        0x7f,
        0xf8,
        0x1e,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x03,
        0x7e,
        0x0f,
        0xf9,
        0xbe,
        0x05,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x01,
        0x7f,
        0xc1,
        0xf3,
        0xfc,
        0x05,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x01,
        0x3d,
        0xf8,
        0x0f,
        0x7c,
        0x05,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x01,
        0xbc,
        0x7f,
        0xff,
        0xf8,
        0x02,
        0xff,
        0xff,
        0xff,
        0xff,
        0xe0,
        0x00,
        0x00,
        0xbe,
        0xff,
        0xff,
        0xf8,
        0x02,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x1d,
        0xff,
        0xff,
        0xf0,
        0x00,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x0f,
        0xf7,
        0xff,
        0xe0,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0xc0,
        0x00,
        0x00,
        0x0f,
        0xf3,
        0xff,
        0xe0,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x00,
        0x03,
        0xf3,
        0xff,
        0xc0,
        0x00,
        0x7f,
        0xff,
        0xff,
        0xff,
        0x80,
        0x00,
        0x00,
        0x01,
        0xf7,
        0xff,
        0x80,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x3f,
        0xff,
        0x00,
        0x00,
        0x3f,
        0xff,
        0xff,
        0xff,
        0x00,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xff,
        0x00,
        0x20,
        0x3f,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xff,
        0x00,
        0x10,
        0x3f,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x00,
        0x00,
        0x1f,
        0xff,
        0x00,
        0x10,
        0x3f,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0x02,
        0x00,
        0x0f,
        0xff,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xfc,
        0x00,
        0x00,
        0x04,
        0x00,
        0x1f,
        0xfe,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x07,
        0x81,
        0x7f,
        0xfe,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x03,
        0xdf,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xf8,
        0x00,
        0x00,
        0x07,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x00,
        0x07,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x1f,
        0xff,
        0xff,
        0xf0,
        0x00,
        0x40,
        0x07,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xf0,
        0x00,
        0xc0,
        0x03,
        0xff,
        0xff,
        0xfe,
        0x00,
        0x00,
        0x0f,
        0xff,
        0xff,
        0xe0,
        0x00,
        0xe0,
        0x07,
        0xff,
        0xff,
        0xfe,
        0x81,
        0x00,
        0x07,
        0xff,
        0xff,
        0xc0,
        0x01,
        0xe0,
        0x07,
        0xff,
        0xff,
        0xfe,
        0x01,
        0x00,
        0x07,
        0xff,
        0xff,
        0x80,
        0x0f,
        0xf0,
        0x03,
        0xff,
        0xff,
        0xfe,
        0x83,
        0x80,
        0x03,
        0xff,
        0xff,
        0x00,
        0x1f,
        0xf0,
        0x13,
        0xff,
        0xff,
        0xfe,
        0x03,
        0xe0,
        0x01,
        0xff,
        0xfc,
        0x03,
        0x3f,
        0xf0,
        0x21,
        0xff,
        0xff,
        0xfe,
        0x03,
        0xfc,
        0x00,
        0x3f,
        0xf0,
        0x3f,
        0x3f,
        0xf8,
        0x3b,
        0xff,
        0xff,
        0xfe,
        0x03,
        0xfe,
        0xc0,
        0x0f,
        0xe3,
        0xfb,
        0x7f,
        0xf8,
        0x3b,
        0xff,
        0xff,
        0xff,
        0x07,
        0xff,
        0xff,
        0x07,
        0x9f,
        0xfb,
        0x7f,
        0xfc,
        0x79,
        0xff,
        0xff,
        0xff,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x7f,
        0xfc,
        0x39,
        0xff,
        0xff,
        0xff,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x7f,
        0xfe,
        0x3f,
        0xff,
        0xff,
        0xfe,
        0x07,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x7f,
        0xfe,
        0x1f,
        0xff,
        0xff,
        0xfe,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x7f,
        0xfe,
        0x1f,
        0x7f,
        0xff,
        0xfe,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x7f,
        0xff,
        0x1f,
        0xfe,
        0xff,
        0xfc,
        0x0f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x0f,
        0xff,
        0xff,
        0xff,
        0x1f,
        0xff,
        0xef,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0x87,
        0xff,
        0xff,
        0xfe,
        0x1f,
        0xff,
        0xef,
        0xff,
        0xff,
        0xff,
        0xbf,
        0xff,
        0x82,
        0xff,
        0xff,
        0xfc,
        0x3f,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xbf,
        0xff,
        0x83,
        0xff,
        0xff,
        0xfc,
        0x3f,
        0xff,
        0xbf,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xc1,
        0xff,
        0xff,
        0xf8,
        0x7f,
        0xff,
        0xbf,
        0xff,
        0xff,
        0xff,
        0xbf,
        0xff,
        0xe0,
        0xff,
        0xff,
        0xf0,
        0xff,
        0xff,
        0xbf,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
        0xff,
    )
)


def getMaskData2():
    return _data2


def doOneBitMaskImages(context):
    bitsPerComponent = 1
    bitsPerPixel = 1
    width = 96
    height = 96
    bytesPerRow = 12

    imageDataSize = bytesPerRow * height
    shouldInterpolate = True
    lightBlue = [0.482, 0.62, 0.871, 1.0]
    black = [0.0, 0.0, 0.0, 1.0]
    darkRed = [0.663, 0.0, 0.031, 1.0]
    darkGreen = [0.404, 0.808, 0.239, 1.0]
    darkBlue = [0.11, 0.208, 0.451, 1.0]
    purple = [0.69, 0.486, 0.722, 1.0]
    darkOrange = [0.965, 0.584, 0.059, 1.0]

    # A decode array contains two elements for each component. In this
    # case, an image mask has one component so the array consists of
    # two values. When using this decode array, a sample value of 0
    # is mapped into the value 1, and the maximum sample value is
    # mapped into the value 0. This inverts the sense of the mask data.
    decode = (1, 0)

    # Create a Quartz data provider for the image data. Because this
    # data is static data, we don't need to release it so the data
    # release function is None.
    data = getMaskData1()
    dataProvider = Quartz.CGDataProviderCreateWithData(None, data, imageDataSize, None)
    if dataProvider is None:
        print("Couldn't create Mask1 Data provider!")
        return

    # Create a mask from the data.
    mask1 = Quartz.CGImageMaskCreate(
        width,
        height,
        bitsPerComponent,
        bitsPerPixel,
        bytesPerRow,
        dataProvider,
        None,
        shouldInterpolate,
    )
    # Create the same mask but with a decode array that
    # inverts the sense of the mask.
    invertedmask1 = Quartz.CGImageMaskCreate(
        width,
        height,
        bitsPerComponent,
        bitsPerPixel,
        bytesPerRow,
        dataProvider,
        decode,
        shouldInterpolate,
    )
    # Release the data provider now that this code no longer needs it.
    del dataProvider

    if mask1 is None or invertedmask1 is None:
        if mask1 is None:
            print("Couldn't create CGImageRef for the mask data 1!")

        if invertedmask1 is None:
            print("Couldn't create CGImageRef for the inverted mask data 1!")
        return

    # Get the pointer to the data for the second mask.
    data = getMaskData2()
    dataProvider = Quartz.CGDataProviderCreateWithData(None, data, imageDataSize, None)
    if dataProvider is None:
        print("Couldn't create Mask2 Data provider!")
        return

    mask2 = Quartz.CGImageMaskCreate(
        width,
        height,
        bitsPerComponent,
        bitsPerPixel,
        bytesPerRow,
        dataProvider,
        None,
        shouldInterpolate,
    )
    # Create the same mask but with a decode array that
    # inverts the sense of the mask.
    invertedmask2 = Quartz.CGImageMaskCreate(
        width,
        height,
        bitsPerComponent,
        bitsPerPixel,
        bytesPerRow,
        dataProvider,
        decode,
        shouldInterpolate,
    )
    # Release the data provider now that this code no longer needs it.
    del dataProvider
    if mask2 is None or invertedmask2 is None:
        if mask2 is None:
            print("Couldn't create CGImageRef for the mask data 2!")

        if invertedmask2 is None:
            print("Couldn't create CGImageRef for the inverted mask data 2!")

        return

    Quartz.CGContextScaleCTM(context, 1.5, 1.5)
    colorSpace = Utilities.getTheCalibratedRGBColorSpace()
    Quartz.CGContextSetFillColorSpace(context, colorSpace)

    # Set the fill color to a light blue.
    Quartz.CGContextSetFillColor(context, lightBlue)
    # Paint part of the background.
    backRect = Quartz.CGRectMake(width / 2, height / 2, width * 3, height)
    Quartz.CGContextFillRect(context, backRect)

    imageRect = Quartz.CGRectMake(0.0, height, width, height)
    Quartz.CGContextSaveGState(context)
    # Set the fill color to opaque black.
    Quartz.CGContextSetFillColor(context, black)
    # Mask 1.
    Quartz.CGContextDrawImage(context, imageRect, mask1)

    Quartz.CGContextTranslateCTM(context, width, 0)
    # Set the fill color to opaque red.
    Quartz.CGContextSetFillColor(context, darkRed)
    # Mask 2.
    Quartz.CGContextDrawImage(context, imageRect, mask2)
    Quartz.CGContextTranslateCTM(context, width, 0)
    # Set the fill color to dark orange.
    Quartz.CGContextSetFillColor(context, darkOrange)
    # Mask 3.
    Quartz.CGContextDrawImage(context, imageRect, mask1)

    Quartz.CGContextTranslateCTM(context, width, 0)
    # Make the orange 50% transparent.
    darkOrange[3] = 0.5
    Quartz.CGContextSetFillColor(context, darkOrange)
    # Mask 4.
    Quartz.CGContextDrawImage(context, imageRect, mask2)
    Quartz.CGContextRestoreGState(context)

    # Translate down the page. The cast is necessary
    # since height is typed as size_t which is unsigned.
    Quartz.CGContextTranslateCTM(context, 0, -height)

    # Set the fill color to an opaque green.
    Quartz.CGContextSetFillColor(context, darkGreen)
    # Mask 5.
    Quartz.CGContextDrawImage(context, imageRect, invertedmask2)

    Quartz.CGContextTranslateCTM(context, width, 0)
    # Set the fill color to a dark blue.
    Quartz.CGContextSetFillColor(context, darkBlue)
    # Mask 6.
    Quartz.CGContextDrawImage(context, imageRect, invertedmask1)
    Quartz.CGContextTranslateCTM(context, width, 0)
    # Set the fill color to purple.
    Quartz.CGContextSetFillColor(context, purple)
    # Mask 7.
    Quartz.CGContextDrawImage(context, imageRect, invertedmask2)
    Quartz.CGContextTranslateCTM(context, width, 0)

    # Make the purple 50% transparent.
    purple[3] = 0.5
    Quartz.CGContextSetFillColor(context, purple)
    # Mask 8.
    Quartz.CGContextDrawImage(context, imageRect, invertedmask1)


def doMaskImageWithMaskFromURL(
    context,
    imageURL,
    imagewidth,
    imageheight,
    bitsPerComponent,
    theMaskingImageURL,
    maskwidth,
    maskheight,
):

    imageBitsPerPixel = bitsPerComponent * 3
    bytesPerRow = ((imagewidth * imageBitsPerPixel) + 7) / 8
    shouldInterpolate = True
    imageDataProvider = Quartz.CGDataProviderCreateWithURL(imageURL)
    if imageDataProvider is None:
        print("Couldn't create Image Data provider!")
        return

    colorspace = Utilities.getTheCalibratedRGBColorSpace()
    image = Quartz.CGImageCreate(
        imagewidth,
        imageheight,
        bitsPerComponent,
        imageBitsPerPixel,
        bytesPerRow,
        colorspace,
        Quartz.kCGImageAlphaNone,
        imageDataProvider,
        None,
        shouldInterpolate,
        Quartz.kCGRenderingIntentDefault,
    )
    del imageDataProvider
    if image is None:
        print("Couldn't create CGImageRef for this data!")
        return

    imageRect = Quartz.CGRectMake(0.0, imageheight, imagewidth, imageheight)
    # Draw the image.
    Quartz.CGContextDrawImage(context, imageRect, image)

    # Now the mask.
    maskDataProvider = Quartz.CGDataProviderCreateWithURL(theMaskingImageURL)
    if maskDataProvider is None:
        print("Couldn't create Image Data provider!")
        return

    mask = Quartz.CGImageMaskCreate(
        maskwidth,
        maskheight,
        bitsPerComponent,
        bitsPerComponent,
        maskwidth,
        maskDataProvider,
        None,
        shouldInterpolate,
    )
    del maskDataProvider
    if mask is None:
        print("Couldn't create CGImageRef for mask data!")
        return

    # Draw the mask below the image. The current fill color (black)
    # is painted through the mask.
    maskRect = Quartz.CGRectMake(0.0, 0.0, maskwidth, maskheight)
    Quartz.CGContextDrawImage(context, maskRect, mask)

    # Create a new CGImage object, the image, masked with mask.
    imageMaskedWithImage = Quartz.CGImageCreateWithMask(image, mask)
    # Once the new image is created, the code can release the image
    # and the mask which make it up. Quartz retains what it needs
    # for the new masked image 'imageMaskedWithImage'.
    del image
    del mask
    if imageMaskedWithImage is None:
        print("Couldn't create image masked with mask!")
        return

    imageRect = Quartz.CGRectMake(
        imagewidth + 10, imageheight / 2, imagewidth, imageheight
    )
    # Draw the masked image to the right of the image and its mask.
    Quartz.CGContextDrawImage(context, imageRect, imageMaskedWithImage)


def doMaskImageWithGrayImageFromURL(
    context,
    imageURL,
    imagewidth,
    imageheight,
    bitsPerComponent,
    theMaskingImageURL,
    maskwidth,
    maskheight,
):

    imageBitsPerPixel = bitsPerComponent * 3
    bytesPerRow = ((imagewidth * imageBitsPerPixel) + 7) / 8
    shouldInterpolate = True

    imageDataProvider = Quartz.CGDataProviderCreateWithURL(imageURL)
    if imageDataProvider is None:
        print("Couldn't create Image Data provider!")
        return

    colorspace = Utilities.getTheCalibratedRGBColorSpace()
    image = Quartz.CGImageCreate(
        imagewidth,
        imageheight,
        bitsPerComponent,
        imageBitsPerPixel,
        bytesPerRow,
        colorspace,
        Quartz.kCGImageAlphaNone,
        imageDataProvider,
        None,
        shouldInterpolate,
        Quartz.kCGRenderingIntentDefault,
    )
    del imageDataProvider
    if image is None:
        print("Couldn't create CGImageRef for this data!")
        return

    imageRect = Quartz.CGRectMake(0.0, imageheight, imagewidth, imageheight)
    # Draw the image.
    Quartz.CGContextDrawImage(context, imageRect, image)

    # Now the mask.
    maskDataProvider = Quartz.CGDataProviderCreateWithURL(theMaskingImageURL)
    if maskDataProvider is None:
        print("Couldn't create Image Data provider!")
        return

    # The color space for the image MUST be DeviceGray for it to
    # be used as a masking image with CGImageCreateWithMask.
    deviceGraySpace = Quartz.CGColorSpaceCreateDeviceGray()
    mask = Quartz.CGImageCreate(
        maskwidth,
        maskheight,
        bitsPerComponent,
        bitsPerComponent,
        maskwidth,
        deviceGraySpace,
        Quartz.kCGImageAlphaNone,
        maskDataProvider,
        None,
        shouldInterpolate,
        Quartz.kCGRenderingIntentDefault,
    )
    # Release the color space since it is no longer needed.
    del deviceGraySpace
    del maskDataProvider

    if mask is None:
        print("Couldn't create CGImageRef for gray image data!")
        return

    # Draw the mask below the image. The current fill color (black)
    # is painted through the mask.
    maskRect = Quartz.CGRectMake(0.0, 0.0, maskwidth, maskheight)
    Quartz.CGContextDrawImage(context, maskRect, mask)

    # Create a new CGImage object, the image, masked with mask.
    imageMaskedWithImage = Quartz.CGImageCreateWithMask(image, mask)

    # Once the new image is created, the code can release the image
    # and the mask which make it up. Quartz retains what it needs
    # for the new masked image 'imageMaskedWithImage'.
    del image
    del mask

    if imageMaskedWithImage is None:
        print("Couldn't create image masked with mask!")
        return

    imageRect = Quartz.CGRectMake(
        imagewidth + 10, imageheight / 2, imagewidth, imageheight
    )
    # Draw the masked image to the right of the image and its mask.
    Quartz.CGContextDrawImage(context, imageRect, imageMaskedWithImage)
    # Be sure and release the masked image.
    del imageMaskedWithImage


def doMaskImageWithColorFromURL(context, url, width, height, isColor):

    # This routine treats color images as RGB.
    bitsPerComponent = 8
    if isColor:
        bitsPerPixel = bitsPerComponent * 3
    else:
        bitsPerPixel = bitsPerComponent

    bytesPerRow = ((width * bitsPerPixel) + 7) / 8
    shouldInterpolate = True

    # This is a range of dark gray to black colors for an 8 bit per component
    # image in a gray or RGB color space. The entries are image sample
    # values of 0-0x1F for the first color component, 0-0x1F for the
    # second color component, and so on. For image sample values where
    # all components fall within the ranges in maskingColors, the sample
    # value is masked and therefore unpainted.
    maskingColors = (0x00, 0x1f, 0x00, 0x1f, 0x00, 0x1f)
    backColor = (1.0, 0.0, 0.0, 1.0)  # Opaque red.

    # Create a Quartz data provider from the supplied URL.
    dataProvider = Quartz.CGDataProviderCreateWithURL(url)
    if dataProvider is None:
        print("Couldn't create Image data provider!")
        return

    # Create an image of the specified width, height and bits per pixel
    # from the URL.
    if isColor:
        colorspace = Utilities.getTheCalibratedRGBColorSpace()
    else:
        colorspace = Utilities.getTheCalibratedGrayColorSpace()

    image = Quartz.CGImageCreate(
        width,
        height,
        bitsPerComponent,
        bitsPerPixel,
        bytesPerRow,
        colorspace,
        Quartz.kCGImageAlphaNone,
        dataProvider,
        None,
        shouldInterpolate,
        Quartz.kCGRenderingIntentDefault,
    )
    del dataProvider
    if image is None:
        print("Couldn't create CGImageRef for this data!")
        return

    imageRect = Quartz.CGRectMake(10.0, 10.0, width, height)
    # Quartz.CGContextScaleCTM(context, 0.33, 0.33)
    # Set the color space and the color, then
    # paint a red rectangle behind the image.
    Quartz.CGContextSetFillColorSpace(context, colorspace)
    Quartz.CGContextSetFillColor(context, backColor)
    Quartz.CGContextFillRect(context, imageRect)
    # Draw the image into the rectangle.
    Quartz.CGContextDrawImage(context, imageRect, image)
    # Create a new image from the original one, masking out a range
    # of the blackest sample values.
    imageMaskedWithColor = Quartz.CGImageCreateWithMaskingColors(image, maskingColors)
    # Release the original image; it is no longer needed.
    del image
    if imageMaskedWithColor is None:
        print("Couldn't create CGImageRef for masking color!")
        return

    # Paint the rectangle behind the next image with red.
    imageRect = Quartz.CGRectMake(30.0 + width, 10.0, width, height)
    Quartz.CGContextFillRect(context, imageRect)
    # Draw the image. Image sample values in the range of
    # the masking color are unpainted, allowing the background
    # to show through.
    Quartz.CGContextDrawImage(context, imageRect, imageMaskedWithColor)


if 1:  # Set to 1 for code in the book.

    def drawWithClippingMask(context, theMaskingImageURL, imagewidth, imageheight):
        # An array of CGColor objects.
        colors = (
            Utilities.getRGBOpaqueDarkGreenColor(),
            Utilities.getRGBOpaqueDarkBlueColor(),
            Utilities.getRGBOpaqueBlueColor(),
            Utilities.getRGBOpaqueRedColor(),
        )

        imageBitsPerComponent = 8
        bytesPerRow = imagewidth
        shouldInterpolate = True
        decode = (1, 0)

        # Create the data.
        dataProvider = Quartz.CGDataProviderCreateWithURL(theMaskingImageURL)
        if dataProvider is None:
            print("Couldn't create Image data provider!")
            return

        cs = Quartz.CGColorSpaceCreateDeviceGray()
        image = Quartz.CGImageCreate(
            imagewidth,
            imageheight,
            imageBitsPerComponent,
            imageBitsPerComponent,
            bytesPerRow,
            cs,
            Quartz.kCGImageAlphaNone,
            dataProvider,
            decode,
            shouldInterpolate,
            Quartz.kCGRenderingIntentDefault,
        )
        del cs
        del dataProvider

        if image is None:
            print("Couldn't create Image!")
            return

        imageRect = Quartz.CGRectMake(0, 0, imagewidth * 2 / 3, imageheight * 2 / 3)

        # Position for drawing the image at the left side of the figure.
        Quartz.CGContextTranslateCTM(context, 50, 50)

        # Draw the image.
        Quartz.CGContextDrawImage(context, imageRect, image)

        # Position to the right of the image just painted.
        Quartz.CGContextTranslateCTM(context, Quartz.CGRectGetWidth(imageRect) + 25, 0)

        # Clip to the image.
        Quartz.CGContextClipToMask(context, imageRect, image)
        # Release the image since this code no longer needs it.
        del image

        # Make a rect that has a width and height 1/3 that of the image.
        rect = Quartz.CGRectMake(
            0,
            0,
            Quartz.CGRectGetWidth(imageRect) / 3,
            Quartz.CGRectGetHeight(imageRect) / 3,
        )

        Quartz.CGContextTranslateCTM(context, 0, 2 * Quartz.CGRectGetHeight(rect))

        # Draw a 3 x 3 grid of rectangles, setting the color for each rectangle
        # by cycling through the array of CGColor objects in the 'colors' array.
        for j in range(3):
            Quartz.CGContextSaveGState(context)
            for i in range(3):
                # Draw a row of rectangles.
                # Set the fill color using one of the CGColor objects in the
                # colors array.
                Quartz.CGContextSetFillColorWithColor(context, colors[(i + j) % 4])
                Quartz.CGContextFillRect(context, rect)
                Quartz.CGContextTranslateCTM(context, Quartz.CGRectGetWidth(rect), 0)

            Quartz.CGContextRestoreGState(context)
            # Position to draw the next row.
            Quartz.CGContextTranslateCTM(context, 0, -Quartz.CGRectGetHeight(rect))


else:
    # This code works just fine to screen but when drawing to a PDF
    # or printing context the masked drawing is completely masked out
    # due to a bug in Quartz prior to Tiger 10.4.3.
    def drawWithClippingMask(context, theMaskingImageURL, maskwidth, maskheight):
        # An array of Quartz.CGColor objects.
        colors = (
            Utilities.getRGBOpaqueDarkGreenColor(),
            Utilities.getRGBOpaqueDarkBlueColor(),
            Utilities.getRGBOpaqueBlueColor(),
            Utilities.getRGBOpaqueRedColor(),
        )
        maskBitsPerComponent = 8
        # bytesPerRow = ((maskwidth * maskBitsPerComponent) + 7) / 8
        shouldInterpolate = True
        maskDataProvider = Quartz.CGDataProviderCreateWithURL(theMaskingImageURL)

        if maskDataProvider is None:
            print("Couldn't create Image Mask provider!")
            return
        mask = Quartz.CGImageMaskCreate(
            maskwidth,
            maskheight,
            maskBitsPerComponent,
            maskBitsPerComponent,
            maskwidth,
            maskDataProvider,
            None,
            shouldInterpolate,
        )
        del maskDataProvider

        if mask is None:
            print("Couldn't create Image Mask!")
            return

        maskRect = Quartz.CGRectMake(0, 0, maskwidth / 3, maskheight / 3)

        # Position for drawing the mask at the left side of the figure.
        Quartz.CGContextTranslateCTM(context, 50, 50)
        # Set the context fill color to a Quartz.CGColor object that is black.
        Quartz.CGContextSetFillColorWithColor(
            context, Utilities.getRGBOpaqueBlackColor()
        )
        # Draw the mask. It is painted with with the black fill color.
        Quartz.CGContextDrawImage(context, maskRect, mask)

        # Position to the right of the mask just painted.
        Quartz.CGContextTranslateCTM(context, Quartz.CGRectGetWidth(maskRect) + 25, 0)

        # Clip to the mask.
        Quartz.CGContextClipToMask(context, maskRect, mask)
        # Release the mask since this code no longer needs it.
        del mask

        # Make a rect that has a width and height 1/3 that of the image mask.
        rect = Quartz.CGRectMake(
            0,
            0,
            Quartz.CGRectGetWidth(maskRect) / 3,
            Quartz.CGRectGetHeight(maskRect) / 3,
        )

        Quartz.CGContextTranslateCTM(context, 0, 2 * Quartz.CGRectGetHeight(rect))

        # Draw a 3 x 3 grid of rectangles, setting the color for each rectangle
        # by cycling through the array of CGColor objects in the 'colors' array.
        for j in range(3):
            Quartz.CGContextSaveGState(context)
            for i in range(3):
                # Draw a row of rectangles.
                # Set the fill color using one of the CGColor objects in the
                # colors array.
                Quartz.CGContextSetFillColorWithColor(context, colors[(i + j) % 4])
                Quartz.CGContextFillRect(context, rect)
                Quartz.CGContextTranslateCTM(context, Quartz.CGRectGetWidth(rect), 0)
            Quartz.CGContextRestoreGState(context)
            # Position to draw the next row.
            Quartz.CGContextTranslateCTM(context, 0, -Quartz.CGRectGetHeight(rect))
