# This file is generated by objective.metadata
#
# Last update: Tue Feb 14 22:21:53 2012

import objc, sys

if sys.maxint > 2 ** 32:
    def sel32or64(a, b): return b
else:
    def sel32or64(a, b): return a
if sys.byteorder == 'little':
    def littleOrBig(a, b): return a
else:
    def littleOrBig(a, b): return b

misc = {
}
constants = '''$PSEnclosureDownloadStateDidChangeNotification$PSErrorDomain$PSFeedAddedEntriesKey$PSFeedDidChangeEntryFlagsKey$PSFeedEntriesChangedNotification$PSFeedRefreshingNotification$PSFeedRemovedEntriesKey$PSFeedUpdatedEntriesKey$'''
enums = '''$PSAtomFormat@2$PSEnclosureDownloadDidFail@4$PSEnclosureDownloadDidFinish@3$PSEnclosureDownloadIsActive@2$PSEnclosureDownloadIsIdle@0$PSEnclosureDownloadIsQueued@1$PSEnclosureDownloadWasDeleted@5$PSFeedSettingsUnlimitedSize@0$PSInternalError@1$PSLinkToAlternate@7$PSLinkToAtom@2$PSLinkToAtomService@3$PSLinkToFOAF@4$PSLinkToOther@0$PSLinkToRSD@5$PSLinkToRSS@1$PSLinkToSelf@6$PSNotAFeedError@2$PSRSSFormat@1$PSUnknownFormat@0$'''
misc.update({'PSFeedSettingsIntervalNever': -1.0, 'PSFeedSettingsAllTypes': None, 'PSFeedSettingsIntervalDefault': 0.0})
r = objc.registerMetaDataForSelector
objc._updatingMetadata(True)
try:
    r('PSClient', b'addFeed:', {'retval': {'type': 'Z'}})
    r('PSClient', b'isPrivate', {'retval': {'type': 'Z'}})
    r('PSClient', b'removeFeed:', {'retval': {'type': 'Z'}})
    r('PSClient', b'setPrivate:', {'arguments': {2: {'type': 'Z'}}})
    r('PSEnclosure', b'download:', {'retval': {'type': 'Z'}, 'arguments': {2: {'type_modifier': b'o'}}})
    r('PSEntry', b'isCurrent', {'retval': {'type': 'Z'}})
    r('PSEntry', b'isFlagged', {'retval': {'type': 'Z'}})
    r('PSEntry', b'isRead', {'retval': {'type': 'Z'}})
    r('PSEntry', b'setFlagged:', {'arguments': {2: {'type': 'Z'}}})
    r('PSEntry', b'setRead:', {'arguments': {2: {'type': 'Z'}}})
    r('PSFeed', b'XMLRepresentationWithEntries:', {'arguments': {2: {'type': 'Z'}}})
    r('PSFeed', b'isRefreshing', {'retval': {'type': 'Z'}})
    r('PSFeed', b'refresh:', {'retval': {'type': 'Z'}, 'arguments': {2: {'type_modifier': b'o'}}})
    r('PSFeedSettings', b'downloadsEnclosures', {'retval': {'type': 'Z'}})
    r('PSFeedSettings', b'refreshesInBackground', {'retval': {'type': 'Z'}})
    r('PSFeedSettings', b'setDownloadsEnclosures:', {'arguments': {2: {'type': 'Z'}}})
    r('PSFeedSettings', b'setRefreshesInBackground:', {'arguments': {2: {'type': 'Z'}}})
finally:
    objc._updatingMetadata(False)
protocols={'PSClientDelegate': objc.informal_protocol('PSClientDelegate', [objc.selector(None, 'feedDidBeginRefresh:', b'v@:@', isRequired=False), objc.selector(None, 'feedDidEndRefresh:', b'v@:@', isRequired=False), objc.selector(None, 'feed:didAddEntries:', b'v@:@@', isRequired=False), objc.selector(None, 'feed:didRemoveEntriesWithIdentifiers:', b'v@:@@', isRequired=False), objc.selector(None, 'feed:didUpdateEntries:', b'v@:@@', isRequired=False), objc.selector(None, 'feed:didChangeFlagsInEntries:', b'v@:@@', isRequired=False), objc.selector(None, 'enclosure:downloadStateDidChange:', b'v@:@i', isRequired=False)])}

# END OF FILE
