#!/usr/bin/env python3.12

import pathlib
import subprocess

TOP_DIR = pathlib.Path(__file__).parent.parent


def main() -> None:
    for item in TOP_DIR.iterdir():
        if not item.name.startswith("pyobjc-framework-"):
            continue
        if not (item / "metadata").exists():
            continue

        print(item.name)
        subprocess.check_call(["objective-metadata-tool", "compile"], cwd=str(item))


if __name__ == "__main__":
    main()
