
from PyObjCTools.TestSupport import *
from LaunchServices import *

class TestUTCoreTypes (TestCase):
    def testConstants(self):
        self.failUnlessIsInstance(kUTTypeItem, unicode)
        self.failUnlessIsInstance(kUTTypeContent, unicode)
        self.failUnlessIsInstance(kUTTypeCompositeContent, unicode)
        self.failUnlessIsInstance(kUTTypeApplication, unicode)
        self.failUnlessIsInstance(kUTTypeMessage, unicode)
        self.failUnlessIsInstance(kUTTypeContact, unicode)
        self.failUnlessIsInstance(kUTTypeArchive, unicode)
        self.failUnlessIsInstance(kUTTypeDiskImage, unicode)
        self.failUnlessIsInstance(kUTTypeData, unicode)
        self.failUnlessIsInstance(kUTTypeDirectory, unicode)
        self.failUnlessIsInstance(kUTTypeResolvable, unicode)
        self.failUnlessIsInstance(kUTTypeSymLink, unicode)
        self.failUnlessIsInstance(kUTTypeMountPoint, unicode)
        self.failUnlessIsInstance(kUTTypeAliasFile, unicode)
        self.failUnlessIsInstance(kUTTypeAliasRecord, unicode)
        self.failUnlessIsInstance(kUTTypeURL, unicode)
        self.failUnlessIsInstance(kUTTypeFileURL, unicode)
        self.failUnlessIsInstance(kUTTypeText, unicode)
        self.failUnlessIsInstance(kUTTypePlainText, unicode)
        self.failUnlessIsInstance(kUTTypeUTF8PlainText, unicode)
        self.failUnlessIsInstance(kUTTypeUTF16ExternalPlainText, unicode)
        self.failUnlessIsInstance(kUTTypeUTF16PlainText, unicode)
        self.failUnlessIsInstance(kUTTypeRTF, unicode)
        self.failUnlessIsInstance(kUTTypeHTML, unicode)
        self.failUnlessIsInstance(kUTTypeXML, unicode)
        self.failUnlessIsInstance(kUTTypeSourceCode, unicode)
        self.failUnlessIsInstance(kUTTypeCSource, unicode)
        self.failUnlessIsInstance(kUTTypeObjectiveCSource, unicode)
        self.failUnlessIsInstance(kUTTypeCPlusPlusSource, unicode)
        self.failUnlessIsInstance(kUTTypeObjectiveCPlusPlusSource, unicode)
        self.failUnlessIsInstance(kUTTypeCHeader, unicode)
        self.failUnlessIsInstance(kUTTypeCPlusPlusHeader, unicode)
        self.failUnlessIsInstance(kUTTypeJavaSource, unicode)
        self.failUnlessIsInstance(kUTTypePDF, unicode)
        self.failUnlessIsInstance(kUTTypeRTFD, unicode)
        self.failUnlessIsInstance(kUTTypeFlatRTFD, unicode)
        self.failUnlessIsInstance(kUTTypeTXNTextAndMultimediaData, unicode)
        self.failUnlessIsInstance(kUTTypeWebArchive, unicode)
        self.failUnlessIsInstance(kUTTypeImage, unicode)
        self.failUnlessIsInstance(kUTTypeJPEG, unicode)
        self.failUnlessIsInstance(kUTTypeJPEG2000, unicode)
        self.failUnlessIsInstance(kUTTypeTIFF, unicode)
        self.failUnlessIsInstance(kUTTypePICT, unicode)
        self.failUnlessIsInstance(kUTTypeGIF, unicode)
        self.failUnlessIsInstance(kUTTypePNG, unicode)
        self.failUnlessIsInstance(kUTTypeQuickTimeImage, unicode)
        self.failUnlessIsInstance(kUTTypeAppleICNS, unicode)
        self.failUnlessIsInstance(kUTTypeBMP, unicode)
        self.failUnlessIsInstance(kUTTypeICO, unicode)
        self.failUnlessIsInstance(kUTTypeAudiovisualContent, unicode)
        self.failUnlessIsInstance(kUTTypeMovie, unicode)
        self.failUnlessIsInstance(kUTTypeVideo, unicode)
        self.failUnlessIsInstance(kUTTypeAudio, unicode)
        self.failUnlessIsInstance(kUTTypeQuickTimeMovie, unicode)
        self.failUnlessIsInstance(kUTTypeMPEG, unicode)
        self.failUnlessIsInstance(kUTTypeMPEG4, unicode)
        self.failUnlessIsInstance(kUTTypeMP3, unicode)
        self.failUnlessIsInstance(kUTTypeMPEG4Audio, unicode)
        self.failUnlessIsInstance(kUTTypeAppleProtectedMPEG4Audio, unicode)
        self.failUnlessIsInstance(kUTTypeFolder, unicode)
        self.failUnlessIsInstance(kUTTypeVolume, unicode)
        self.failUnlessIsInstance(kUTTypePackage, unicode)
        self.failUnlessIsInstance(kUTTypeBundle, unicode)
        self.failUnlessIsInstance(kUTTypeFramework, unicode)
        self.failUnlessIsInstance(kUTTypeApplicationBundle, unicode)
        self.failUnlessIsInstance(kUTTypeApplicationFile, unicode)
        self.failUnlessIsInstance(kUTTypeVCard, unicode)
        self.failUnlessIsInstance(kUTTypeInkText, unicode)

if __name__ == "__main__":
    main()
