import QTKit
from PyObjCTools.TestSupport import TestCase, min_os_level, expectedFailure


class TestQTMetadaItem(TestCase):
    @min_os_level("10.7")
    def testConstants10_7(self):
        self.assertIsInstance(QTKit.QTMetadataFormatQuickTimeUserData, str)
        self.assertIsInstance(QTKit.QTMetadataFormatQuickTimeMetadata, str)
        self.assertIsInstance(QTKit.QTMetadataFormatiTunesMetadata, str)
        self.assertIsInstance(QTKit.QTMetadataFormatID3Metadata, str)
        self.assertIsInstance(QTKit.QTMetadataKeySpaceCommon, str)
        self.assertIsInstance(QTKit.QTMetadataKeySpaceQuickTimeUserData, str)
        self.assertIsInstance(QTKit.QTMetadataKeySpaceQuickTimeMetadata, str)
        self.assertIsInstance(QTKit.QTMetadataKeySpaceiTunes, str)
        self.assertIsInstance(QTKit.QTMetadataKeySpaceID3, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyTitle, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyCreator, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeySubject, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyDescription, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyPublisher, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyContributor, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyCreationDate, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyLastModifiedDate, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyType, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyFormat, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyIdentifier, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeySource, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyLanguage, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyRelation, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyLocation, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyCopyrights, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyAlbumName, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyAuthor, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyArtist, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyArtwork, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyMake, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyModel, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeySoftware, str)
        self.assertIsInstance(QTKit.QTMetadataCommonKeyComment, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyAlbum, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyArranger, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyArtist, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyAuthor, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyChapter, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyComment, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyComposer, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyCopyright, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyCreationDate, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyDescription, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyDirector, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyDisclaimer, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyEncodedBy, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyFullName, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyGenre, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyHostComputer, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyInformation, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyKeywords, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyMake, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyModel, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyOriginalArtist, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyOriginalFormat, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyOriginalSource, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyPerformers, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyProducer, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyPublisher, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyProduct, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeySoftware, str)
        self.assertIsInstance(
            QTKit.QTMetadataQuickTimeUserDataKeySpecialPlaybackRequirements, str
        )
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyTrack, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyWarning, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyWriter, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyURLLink, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyLocationISO6709, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyTrackName, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyCredits, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeUserDataKeyPhonogramRights, str)
        self.assertIsInstance(QTKit.QTMetadataISOUserDataKeyCopyright, str)
        self.assertIsInstance(QTKit.QTMetadata3GPUserDataKeyCopyright, str)
        self.assertIsInstance(QTKit.QTMetadata3GPUserDataKeyAuthor, str)
        self.assertIsInstance(QTKit.QTMetadata3GPUserDataKeyPerformer, str)
        self.assertIsInstance(QTKit.QTMetadata3GPUserDataKeyGenre, str)
        self.assertIsInstance(QTKit.QTMetadata3GPUserDataKeyRecordingYear, str)
        self.assertIsInstance(QTKit.QTMetadata3GPUserDataKeyLocation, str)
        self.assertIsInstance(QTKit.QTMetadata3GPUserDataKeyTitle, str)
        self.assertIsInstance(QTKit.QTMetadata3GPUserDataKeyDescription, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyAuthor, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyComment, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyCopyright, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyCreationDate, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyDirector, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyDisplayName, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyInformation, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyKeywords, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyProducer, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyPublisher, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyAlbum, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyArtist, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyArtwork, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyDescription, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeySoftware, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyYear, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyGenre, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyiXML, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyLocationISO6709, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyMake, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyModel, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyArranger, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyEncodedBy, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyOriginalArtist, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyPerformer, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyComposer, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyCredits, str)
        self.assertIsInstance(QTKit.QTMetadataQuickTimeMetadataKeyPhonogramRights, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyAlbum, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyArtist, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyUserComment, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyCoverArt, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyCopyright, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyReleaseDate, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyEncodedBy, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyPredefinedGenre, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyUserGenre, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeySongName, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyTrackSubTitle, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyEncodingTool, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyComposer, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyAlbumArtist, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyAccountKind, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyAppleID, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyArtistID, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeySongID, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyDiscCompilation, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyDiscNumber, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyGenreID, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyGrouping, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyPlaylistID, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyContentRating, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyBeatsPerMin, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyTrackNumber, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyArtDirector, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyArranger, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyAuthor, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyLyrics, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyAcknowledgement, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyConductor, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyDescription, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyDirector, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyEQ, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyLinerNotes, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyRecordCompany, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyOriginalArtist, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyPhonogramRights, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyProducer, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyPerformer, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyPublisher, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeySoundEngineer, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeySoloist, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyCredits, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyThanks, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyOnlineExtras, str)
        self.assertIsInstance(QTKit.QTMetadataiTunesMetadataKeyExecProducer, str)

    @expectedFailure
    @min_os_level("10.7")
    def testConstants10_7_missing(self):
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyAudioEncryption, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyAttachedPicture, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyAudioSeekPointIndex, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyComments, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyCommerical, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyEncryption, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyEqualization, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyEqualization2, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyEventTimingCodes, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyGeneralEncapsulatedObject, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyGroupIdentifier, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyInvolvedPeopleList_v23, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyLink, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyMusicCDIdentifier, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyMPEGLocationLookupTable, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyOwnership, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyPrivate, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyPlayCounter, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyPopularimeter, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyPositionSynchronization, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyRecommendedBufferSize, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyRelativeVolumeAdjustment, str
        )
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyRelativeVolumeAdjustment2, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyReverb, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeySeek, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeySignature, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeySynchronizedLyric, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeySynchronizedTempoCodes, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyAlbumTitle, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyBeatsPerMinute, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyComposer, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyContentType, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyCopyright, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyDate, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyEncodingTime, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyPlaylistDelay, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyOriginalReleaseTime, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyRecordingTime, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyReleaseTime, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyTaggingTime, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyEncodedBy, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyLyricist, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyFileType, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyTime, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyInvolvedPeopleList_v24, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyContentGroupDescription, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyTitleDescription, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeySubTitle, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyInitialKey, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyLanguage, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyLength, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyMusicianCreditsList, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyMediaType, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyMood, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyOriginalAlbumTitle, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyOriginalFilename, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyOriginalLyricist, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyOriginalArtist, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyOriginalReleaseYear, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyFileOwner, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyLeadPerformer, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyBand, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyConductor, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyModifiedBy, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyPartOfASet, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyProducedNotice, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyPublisher, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyTrackNumber, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyRecordingDates, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyInternetRadioStationName, str
        )
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyInternetRadioStationOwner, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeySize, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyAlbumSortOrder, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyPerformerSortOrder, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyTitleSortOrder, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyInternationalStandardRecordingCode, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyEncodedWith, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeySetSubtitle, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyYear, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyUserText, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyUniqueFileIdentifier, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyTermsOfUse, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyUnsynchronizedLyric, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyCommercialInformation, str)
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyCopyrightInformation, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyOfficialAudioFileWebpage, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyOfficialArtistWebpage, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyOfficialAudioSourceWebpage, str
        )
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyOfficialInternetRadioStationHomepage, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyPayment, str)
        self.assertIsInstance(
            QTKit.QTMetadataID3MetadataKeyOfficialPublisherWebpage, str
        )
        self.assertIsInstance(QTKit.QTMetadataID3MetadataKeyUserURL, str)
