from PyObjCTools.TestSupport import TestCase, fourcc
import QTKit


class TestQTKitDefines(TestCase):
    def testConstants(self):
        self.assertEqual(QTKit.QTKIT_VERSION_7_0, 70000)
        self.assertEqual(QTKit.QTKIT_VERSION_7_2, 70200)
        self.assertEqual(QTKit.QTKIT_VERSION_7_6_3, 70603)
        self.assertEqual(QTKit.QTKIT_VERSION_7_6_6, 70606)
        self.assertEqual(QTKit.QTKIT_VERSION_7_7, 70700)
        self.assertEqual(QTKit.QTKIT_VERSION_7_7_2, 70702)
        self.assertEqual(QTKit.QTKIT_VERSION_7_7_3, 70703)

        self.assertEqual(QTKit.VideoMediaType, fourcc(b"vide"))
        self.assertEqual(QTKit.SoundMediaType, fourcc(b"soun"))
        self.assertEqual(QTKit.TextMediaType, fourcc(b"text"))
        self.assertEqual(QTKit.BaseMediaType, fourcc(b"gnrc"))
        self.assertEqual(QTKit.MPEGMediaType, fourcc(b"MPEG"))
        self.assertEqual(QTKit.MusicMediaType, fourcc(b"musi"))
        self.assertEqual(QTKit.TimeCodeMediaType, fourcc(b"tmcd"))
        self.assertEqual(QTKit.SpriteMediaType, fourcc(b"sprt"))
        self.assertEqual(QTKit.FlashMediaType, fourcc(b"flsh"))
        self.assertEqual(QTKit.MovieMediaType, fourcc(b"moov"))
        self.assertEqual(QTKit.TweenMediaType, fourcc(b"twen"))
        self.assertEqual(QTKit.ThreeDeeMediaType, fourcc(b"qd3d"))
        self.assertEqual(QTKit.SkinMediaType, fourcc(b"skin"))
        self.assertEqual(QTKit.HandleDataHandlerSubType, fourcc(b"hndl"))
        self.assertEqual(QTKit.PointerDataHandlerSubType, fourcc(b"ptr "))
        self.assertEqual(QTKit.NullDataHandlerSubType, fourcc(b"null"))
        self.assertEqual(QTKit.ResourceDataHandlerSubType, fourcc(b"rsrc"))
        self.assertEqual(QTKit.URLDataHandlerSubType, fourcc(b"url "))
        self.assertEqual(QTKit.AliasDataHandlerSubType, fourcc(b"alis"))
        self.assertEqual(QTKit.WiredActionHandlerType, fourcc(b"wire"))
        self.assertEqual(QTKit.kQTQuartzComposerMediaType, fourcc(b"qtz "))
        self.assertEqual(QTKit.TimeCode64MediaType, fourcc(b"tc64"))

        self.assertEqual(QTKit.kQTFileTypeAIFF, fourcc(b"AIFF"))
        self.assertEqual(QTKit.kQTFileTypeAIFC, fourcc(b"AIFC"))
        self.assertEqual(QTKit.kQTFileTypeDVC, fourcc(b"dvc!"))
        self.assertEqual(QTKit.kQTFileTypeMIDI, fourcc(b"Midi"))
        self.assertEqual(QTKit.kQTFileTypePicture, fourcc(b"PICT"))
        self.assertEqual(QTKit.kQTFileTypeMovie, fourcc(b"MooV"))
        self.assertEqual(QTKit.kQTFileTypeText, fourcc(b"TEXT"))
        self.assertEqual(QTKit.kQTFileTypeWave, fourcc(b"WAVE"))
        self.assertEqual(QTKit.kQTFileTypeSystemSevenSound, fourcc(b"sfil"))
        self.assertEqual(QTKit.kQTFileTypeMuLaw, fourcc(b"ULAW"))
        self.assertEqual(QTKit.kQTFileTypeAVI, fourcc(b"VfW "))
        self.assertEqual(QTKit.kQTFileTypeSoundDesignerII, fourcc(b"Sd2f"))
        self.assertEqual(QTKit.kQTFileTypeAudioCDTrack, fourcc(b"trak"))
        self.assertEqual(QTKit.kQTFileTypePICS, fourcc(b"PICS"))
        self.assertEqual(QTKit.kQTFileTypeGIF, fourcc(b"GIFf"))
        self.assertEqual(QTKit.kQTFileTypePNG, fourcc(b"PNGf"))
        self.assertEqual(QTKit.kQTFileTypeTIFF, fourcc(b"TIFF"))
        self.assertEqual(QTKit.kQTFileTypePhotoShop, fourcc(b"8BPS"))
        self.assertEqual(QTKit.kQTFileTypeSGIImage, fourcc(b".SGI"))
        self.assertEqual(QTKit.kQTFileTypeBMP, fourcc(b"BMPf"))
        self.assertEqual(QTKit.kQTFileTypeJPEG, fourcc(b"JPEG"))
        self.assertEqual(QTKit.kQTFileTypeJFIF, fourcc(b"JPEG"))
        self.assertEqual(QTKit.kQTFileTypeMacPaint, fourcc(b"PNTG"))
        self.assertEqual(QTKit.kQTFileTypeTargaImage, fourcc(b"TPIC"))
        self.assertEqual(QTKit.kQTFileTypeQuickDrawGXPicture, fourcc(b"qdgx"))
        self.assertEqual(QTKit.kQTFileTypeQuickTimeImage, fourcc(b"qtif"))
        self.assertEqual(QTKit.kQTFileType3DMF, fourcc(b"3DMF"))
        self.assertEqual(QTKit.kQTFileTypeFLC, fourcc(b"FLC "))
        self.assertEqual(QTKit.kQTFileTypeFlash, fourcc(b"SWFL"))
        self.assertEqual(QTKit.kQTFileTypeFlashPix, fourcc(b"FPix"))
        self.assertEqual(QTKit.kQTFileTypeMP4, fourcc(b"mpg4"))
        self.assertEqual(QTKit.kQTFileTypePDF, fourcc(b"PDF "))
        self.assertEqual(QTKit.kQTFileType3GPP, fourcc(b"3gpp"))
        self.assertEqual(QTKit.kQTFileTypeAMR, fourcc(b"amr "))
        self.assertEqual(QTKit.kQTFileTypeSDV, fourcc(b"sdv "))
        self.assertEqual(QTKit.kQTFileType3GP2, fourcc(b"3gp2"))
        self.assertEqual(QTKit.kQTFileTypeAMC, fourcc(b"amc "))
        self.assertEqual(QTKit.kQTFileTypeJPEG2000, fourcc(b"jp2 "))
        self.assertEqual(QTKit.codecLosslessQuality, 0x00000400)
        self.assertEqual(QTKit.codecMaxQuality, 0x000003FF)
        self.assertEqual(QTKit.codecMinQuality, 0x00000000)
        self.assertEqual(QTKit.codecLowQuality, 0x00000100)
        self.assertEqual(QTKit.codecNormalQuality, 0x00000200)
        self.assertEqual(QTKit.codecHighQuality, 0x00000300)
        self.assertEqual(QTKit.kRawCodecType, fourcc(b"raw "))
        self.assertEqual(QTKit.kCinepakCodecType, fourcc(b"cvid"))
        self.assertEqual(QTKit.kGraphicsCodecType, fourcc(b"smc "))
        self.assertEqual(QTKit.kAnimationCodecType, fourcc(b"rle "))
        self.assertEqual(QTKit.kVideoCodecType, fourcc(b"rpza"))
        self.assertEqual(QTKit.kComponentVideoCodecType, fourcc(b"yuv2"))
        self.assertEqual(QTKit.kJPEGCodecType, fourcc(b"jpeg"))
        self.assertEqual(QTKit.kMotionJPEGACodecType, fourcc(b"mjpa"))
        self.assertEqual(QTKit.kMotionJPEGBCodecType, fourcc(b"mjpb"))
        self.assertEqual(QTKit.kSGICodecType, fourcc(b".SGI"))
        self.assertEqual(QTKit.kPlanarRGBCodecType, fourcc(b"8BPS"))
        self.assertEqual(QTKit.kMacPaintCodecType, fourcc(b"PNTG"))
        self.assertEqual(QTKit.kGIFCodecType, fourcc(b"gif "))
        self.assertEqual(QTKit.kPhotoCDCodecType, fourcc(b"kpcd"))
        self.assertEqual(QTKit.kQuickDrawGXCodecType, fourcc(b"qdgx"))
        self.assertEqual(QTKit.kAVRJPEGCodecType, fourcc(b"avr "))
        self.assertEqual(QTKit.kOpenDMLJPEGCodecType, fourcc(b"dmb1"))
        self.assertEqual(QTKit.kBMPCodecType, fourcc(b"WRLE"))
        self.assertEqual(QTKit.kWindowsRawCodecType, fourcc(b"WRAW"))
        self.assertEqual(QTKit.kVectorCodecType, fourcc(b"path"))
        self.assertEqual(QTKit.kQuickDrawCodecType, fourcc(b"qdrw"))
        self.assertEqual(QTKit.kWaterRippleCodecType, fourcc(b"ripl"))
        self.assertEqual(QTKit.kFireCodecType, fourcc(b"fire"))
        self.assertEqual(QTKit.kCloudCodecType, fourcc(b"clou"))
        self.assertEqual(QTKit.kH261CodecType, fourcc(b"h261"))
        self.assertEqual(QTKit.kH263CodecType, fourcc(b"h263"))
        self.assertEqual(QTKit.kDVCNTSCCodecType, fourcc(b"dvc "))
        self.assertEqual(QTKit.kDVCPALCodecType, fourcc(b"dvcp"))
        self.assertEqual(QTKit.kDVCProPALCodecType, fourcc(b"dvpp"))
        self.assertEqual(QTKit.kDVCPro50NTSCCodecType, fourcc(b"dv5n"))
        self.assertEqual(QTKit.kDVCPro50PALCodecType, fourcc(b"dv5p"))
        # self.assertEqual(QTKit.kDVCPro100NTSCCodecType, fourcc(b'dv1n'))
        self.assertEqual(QTKit.kDVCPro100PALCodecType, fourcc(b"dv1p"))
        self.assertEqual(QTKit.kDVCPROHD720pCodecType, fourcc(b"dvhp"))
        self.assertEqual(QTKit.kDVCPROHD1080i60CodecType, fourcc(b"dvh6"))
        self.assertEqual(QTKit.kDVCPROHD1080i50CodecType, fourcc(b"dvh5"))
        self.assertEqual(QTKit.kBaseCodecType, fourcc(b"base"))
        self.assertEqual(QTKit.kFLCCodecType, fourcc(b"flic"))
        self.assertEqual(QTKit.kTargaCodecType, fourcc(b"tga "))
        self.assertEqual(QTKit.kPNGCodecType, fourcc(b"png "))
        self.assertEqual(QTKit.kTIFFCodecType, fourcc(b"tiff"))
        self.assertEqual(QTKit.kComponentVideoSigned, fourcc(b"yuvu"))
        self.assertEqual(QTKit.kComponentVideoUnsigned, fourcc(b"yuvs"))
        self.assertEqual(QTKit.kCMYKCodecType, fourcc(b"cmyk"))
        self.assertEqual(QTKit.kMicrosoftVideo1CodecType, fourcc(b"msvc"))
        self.assertEqual(QTKit.kSorensonCodecType, fourcc(b"SVQ1"))
        self.assertEqual(QTKit.kSorenson3CodecType, fourcc(b"SVQ3"))
        self.assertEqual(QTKit.kIndeo4CodecType, fourcc(b"IV41"))
        self.assertEqual(QTKit.kMPEG4VisualCodecType, fourcc(b"mp4v"))
        self.assertEqual(QTKit.k64ARGBCodecType, fourcc(b"b64a"))
        self.assertEqual(QTKit.k48RGBCodecType, fourcc(b"b48r"))
        self.assertEqual(QTKit.k32AlphaGrayCodecType, fourcc(b"b32a"))
        self.assertEqual(QTKit.k16GrayCodecType, fourcc(b"b16g"))
        self.assertEqual(QTKit.kMpegYUV420CodecType, fourcc(b"myuv"))
        self.assertEqual(QTKit.kYUV420CodecType, fourcc(b"y420"))
        self.assertEqual(QTKit.kSorensonYUV9CodecType, fourcc(b"syv9"))
        self.assertEqual(QTKit.k422YpCbCr8CodecType, fourcc(b"2vuy"))
        self.assertEqual(QTKit.k444YpCbCr8CodecType, fourcc(b"v308"))
        self.assertEqual(QTKit.k4444YpCbCrA8CodecType, fourcc(b"v408"))
        self.assertEqual(QTKit.k422YpCbCr16CodecType, fourcc(b"v216"))
        self.assertEqual(QTKit.k422YpCbCr10CodecType, fourcc(b"v210"))
        self.assertEqual(QTKit.k444YpCbCr10CodecType, fourcc(b"v410"))
        self.assertEqual(QTKit.k4444YpCbCrA8RCodecType, fourcc(b"r408"))
        self.assertEqual(QTKit.kJPEG2000CodecType, fourcc(b"mjp2"))
        self.assertEqual(QTKit.kPixletCodecType, fourcc(b"pxlt"))
        self.assertEqual(QTKit.kH264CodecType, fourcc(b"avc1"))
        self.assertEqual(QTKit.graphicsModeStraightAlpha, 256)
        self.assertEqual(QTKit.graphicsModePreWhiteAlpha, 257)
        self.assertEqual(QTKit.graphicsModePreBlackAlpha, 258)
        self.assertEqual(QTKit.graphicsModeComposition, 259)
        self.assertEqual(QTKit.graphicsModeStraightAlphaBlend, 260)
        self.assertEqual(QTKit.graphicsModePreMulColorAlpha, 261)
        self.assertEqual(QTKit.graphicsModePerComponentAlpha, 272)
