#!/bin/sh

# This script uses Apple's 'headerdoc' tool to create HTML documentation for
# the bridge. The documentation is for developers only.
#
BASEDIR="$(dirname "$(dirname "${0}")")"

if [ ! -d "${BASEDIR}/Doc/headerdoc" ]; then
	mkdir "${BASEDIR}/Doc/headerdoc"
fi

headerdoc2html -o "${BASEDIR}/Doc/headerdoc" "${BASEDIR}/Modules/objc"
gatherheaderdoc "${BASEDIR}/Doc/headerdoc"

# An annoying feature of headerdoc is that you cannot specify a different
# configuration, it always picks up its configuration from ~/Library/Preferences
mv "${BASEDIR}/Doc/headerdoc/MasterTOC.html" "${BASEDIR}/Doc/headerdoc/index.html"

exit 0
