# This file is generated by objective.metadata
#
# Last update: Mon Jul 18 14:03:52 2016

import objc, sys

if sys.maxsize > 2 ** 32:
    def sel32or64(a, b): return b
else:
    def sel32or64(a, b): return a
if sys.byteorder == 'little':
    def littleOrBig(a, b): return a
else:
    def littleOrBig(a, b): return b

misc = {
}
constants = '''$$'''
enums = '''$PHLivePhotoViewContentModeAspectFill@1$PHLivePhotoViewContentModeAspectFit@0$PHLivePhotoViewPlaybackStyleFull@1$PHLivePhotoViewPlaybackStyleHint@2$PHLivePhotoViewPlaybackStyleUndefined@0$'''
misc.update({})
r = objc.registerMetaDataForSelector
objc._updatingMetadata(True)
try:
    r(b'NSObject', b'canHandleAdjustmentData:', {'retval': {'type': 'Z'}})
    r(b'NSObject', b'finishContentEditingWithCompletionHandler:', {'arguments': {2: {'callable': {'retval': {'type': b'v'}, 'arguments': {0: {'type': b'^v'}, 1: {'type': b'@'}}}, 'type': '@?'}}})
    r(b'NSObject', b'livePhotoView:didEndPlaybackWithStyle:', {'arguments': {3: {'type': sel32or64(b'i', b'q')}}})
    r(b'NSObject', b'livePhotoView:willBeginPlaybackWithStyle:', {'arguments': {3: {'type': sel32or64(b'i', b'q')}}})
    r(b'NSObject', b'shouldShowCancelConfirmation', {'retval': {'type': 'Z'}})
    r(b'PHLivePhotoView', b'isMuted', {'retval': {'type': 'Z'}})
    r(b'PHLivePhotoView', b'setMuted:', {'arguments': {2: {'type': 'Z'}}})
    r(b'PHLivePhotoView', b'stopPlaybackAnimated:', {'arguments': {2: {'type': 'Z'}}})
finally:
    objc._updatingMetadata(False)
expressions = {}

# END OF FILE
